### ISSUE TITLE
raise RuntimeError('This event loop is already running')

### ISSUE THREAD

**Issue by kennyjudo** [hbldh/bleak#10]
* bleak version: 
* Python version: 3.6.5
* Operating System: win10 Spyder 3.6.8

### Description
I try the LE device scan example get the error message in Spyder 3.6.8 as title mentioned, the program can should the nearly LE devices name and ID but it out of control after the output, just hang........ 

please anyone can help? 
```

**Comment by hbldh** [comment]
I think this is an [issue](https://stackoverflow.com/questions/50243393/runtimeerror-this-event-loop-is-already-running-debugging-aiohttp-asyncio-a) with Spyder I am afraid. It seems that Spyder uses event loops internally to run the code, and this will never work with Bleak.

Try running the code from `cmd` instead and see if it works, or switch to another IDE, e.g. PyCharm where I know that it works.

**Comment by kennyjudo** [comment]
Yes. I use the same code in vscode without runtime error, I may switch to
vscode since it’s support anaconda.

「Henrik Blidh <notifications@github.com>」在 2018年6月27日 週三，21:01 寫道：

**Comment by hbldh** [comment]
Good that it works! Closing issue.
