### ISSUE TITLE
Issues with devices that allow a single connection

### ISSUE THREAD

**Issue by arasan90** [hbldh/bleak#103]
* bleak version: 0.5
* Python version: 3.7.4
* Operating System: Win10

### Description

Trying to connect to device.
When i try connecting to the device (this device will close the server as soon as a client will disconnect) this device disappears from the detected devices list (i'm checking that with a mobile app). It looks like the call to `bleak.BleakClient(address, loop=loop)` performs a connection of some sort and then disconnects.

### What I Did

`async def connect(address, loop):`
        `async with bleak.BleakClient(address, loop=loop) as client:`
                `await client.connect()`
                `print("Device is %d" % client.is_connected())`

**Comment by hbldh** [comment]
If you run the code you supplied:

```python
async def connect(address, loop):
    async with bleak.BleakClient(address, loop=loop) as client:
        await client.connect()
        print("Device is %d" % client.is_connected()
```

FIrst of all, the `connect` method is not needed when using the `async with` statement. The connect is part of the [`__aenter__` method](https://github.com/hbldh/bleak/blob/master/bleak/backends/client.py#L40-L42), which is called on `async with`.

Secondly, once your code exists the `async with`-scope, the [method `__aexit`](https://github.com/hbldh/bleak/blob/master/bleak/backends/client.py#L44-L45) will be called, disconnecting the Bleak client from the device. You have to do something inside the `async with` context manager to keep the code running.

Look through the [examples](https://github.com/hbldh/bleak/tree/master/examples) folder to see how it is done there. You might also have a look at [Async IO in Python: A Complete Walkthrough](https://realpython.com/async-io-python/) and [Python Context Managers and the "with" Statement](https://realpython.com/courses/python-context-managers-and-with-statement/) for some pointers. 

Good luck!
