### ISSUE TITLE
Wrong BlueZ version check in write_gatt_char

### ISSUE THREAD

**Issue by arthur-proglove** [hbldh/bleak#106]
* bleak version: 0.5.1.dev1
* Python version: 3.7.3
* Operating System: Ubuntu 19.04
* BlueZ version: 5.50

### Description

In the method `write_gatt_char`, the `WriteValue` command is only called if the write request is with response or if the BlueZ version is strictly greater then `5.50`. Shouldn't this be greater or equal to `5.50`?

```
if response or (self._bluez_version[0] == 5 and self._bluez_version[1] > 50):                                                                          
```

**Comment by hbldh** [comment]
Hello, no I think the version boundary is correct. See the `WriteValue` in the docs of the `5.50`-tagged [commit](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt?h=5.50) and contrast that to the [current master branch docs](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt).
