### ISSUE TITLE
Proper way to manage reconnects

### ISSUE THREAD

**Issue by progerzua** [hbldh/bleak#110]
* bleak version: 0.5.0
* Python version: 3.6.8
* Operating System: Ubuntu 18.04.2 LTS

### Description

What is the right and preferred way to manage reconnects?

I thought about something like this:
```
async def run(address, loop):
    async with BleakClient(address, loop=loop) as client:
         while True:
               if isconnected:
                       mac_addr_char = await client.read_gatt_char(uiids.MAC_ADDRESS_UIID)
                       await asyncio.sleep(0.5)
                else:
                        print('disconnected, trying to connect', time.time())
                        devices = await discover()
                        if mydevice in devices:
                              await client.connect()
                        await asyncio.sleep(1)
```

The only problem is here, that 'connect' method could work forever in case if device disappeared.

I saw another solution, which described here: https://github.com/hbldh/bleak/issues/108 .

> I am maintaining multiple BLEClients to multiple devices that get in and out of range regularly. If I have a connection to a device I discover, I do nothing, else I create a new BleakClient object.

>On disconnect I call .disconnect() and delete the Object.

### Summary
Which one of these two solutions is preferred and works the same way as Android\iOs devices? I`m using this library to make unittests for BLE device.

**Comment by hbldh** [comment]
> "works the same way as Android\iOs devices"

I have no idea. I have never coded BLE on those platforms.

>"Which one of these two solutions is preferred"

Whichever one suits you needs best. I personally have never used the "forever connected" solution, so I have never explored this topic. I prefer disposing of my BleakClients and creating new ones, since then I know that there are no old settings present and that the potential of identical behaviour is largest.
