### ISSUE TITLE
Bleak CoreBluetooth backend is leaking tasks?

### ISSUE THREAD

**Issue by zyv** [hbldh/bleak#111]
* bleak version: 0.5.0
* Python version: Python 3.7.4
* Operating System: macOS Mojave 10.14.6 (18G87)

### Description

If I close the event loop after using Bleak and disconnecting from the device, I get an error from asyncio saying that it destroyed a pending task:

```
DEBUG:bleak.backends.corebluetooth.CentralManagerDelegate:Peripheral Device disconnected!
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Application._handle_nsrunloop() running at /Users/zaytsev/PycharmProjects/huawei-lpv2/venv/lib/python3.7/site-packages/bleak/backends/corebluetooth/__init__.py:45>>
```

### What I Did

```
    event_loop = asyncio.get_event_loop()

    try:
        event_loop.run_until_complete(run(...))
    finally:
        event_loop.close()
```

**Comment by hbldh** [comment]
Try adding a
```python
from bleak.backends.corebluetooth.client import cbapp
cbapp.ns_run_loop_done = True
await event_loop.sleep(0.1)
```
somewhere in the end of your `run` method.

That might remove the warning.

**Comment by hbldh** [comment]
Have not heard this from anyone else since. Will close for now.

**Comment by dlech** [comment]
This only halfway fixes the problem `_central_manager_delegate_ready` can still be pending.
