### ISSUE TITLE
Is it possible to force subscribe on indication?

### ISSUE THREAD

**Issue by progerzua** [hbldh/bleak#113]
* bleak version: 0.5.0
* Python version:
* Operating System:

### Description

I'm working with BLE device, which have Notification and Indication on the same characteristic. By default, bleak subscribes on Notification, and thus I`m getting always only the first packet, and never got others.

Probably, thats a problem of bluez DBus implementation, but is it possible to force use Indication instead of Notification?

The same code on Windows works perfectly, but on Windows Indications have higher priority because of different backend.

**Comment by hbldh** [comment]
- In the Windows Bluetooth API it is not possible to select; and it will select indications if it is available as you say.
- In the BlueZ backend I do not know if it is possible to select, but I think not. I had thought it also used indications if possible, but apparently not.
- In the Core Buetooth backend I have no idea what is default.

Bleak uses native Bluetooth LE APIs on every platform and therefore has a more diverse spectra of behaviour. Noble is a much more mature project and selected a different way to handle BLE communication.
