### ISSUE TITLE
How to get RSSI after connecting to BLE device

### ISSUE THREAD

**Issue by mobier** [hbldh/bleak#1131]
* bleak version:  0.19.4
* Python version: 3.9.2
* Operating System: Raspbian GNU/Linux 11
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.55

### Description

I try to read the RSSI after connection using this function
`bleak/backends/corebluetooth/client.py#get_rssi()`

I get this error after running
AttributeError: 'BleakClient' object has no attribute 'get_rssi'
'''
    if platform.system() == "Darwin":
        from bleak.backends.corebluetooth.client import BleakClientCoreBluetooth
'''
I found that the `get_rssi` function is only available under the Darwin system. I would like to ask if it can support Linux or is there any other way to achieve it?

**Comment by dlech** [comment]
As already discussed in #879, since this is currently only available on one OS, we don't plan to support it. Some alternatives are mentioned there.
