### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by alexwhittemore** [hbldh/bleak#115]
* bleak version: 0.5.0
* Python version: 3.7.4 
* Operating System: 10.14.6

### Description

You can pretty much close this issue as soon as you've seen it, I just wanted to say thanks!

This is the only cross-platform BLE library I've come across after somewhat extensive searching that can deliver on my `hello world` requirement of "list local devices" with no drama. Thanks for all the good work, and documentation :)

### What I Did

```
mkvirtualenv -p python3 bleak
pip install bleak
```
Ran the following python file:
```
import asyncio
from bleak import discover

async def run():
    devices = await discover()
    for d in devices:
        print(d)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```
Got a list of devices nearby :)

**Comment by hbldh** [comment]
Thank you! I cannot wholeheartedly join in the "good documentation" praise, but I do my best in that regard. The code itself is better than i originally envisioned it, at least the "pip install"-only requirement of the package.
