### ISSUE TITLE
Generic Access Profile not being discovered on MacOS

### ISSUE THREAD

**Issue by andrewgrabbs** [hbldh/bleak#1189]
* bleak version: 0.11.0
* Python version: Python 3.9.13
* Operating System: MacOS Ventura 13.0.1 (22A400)
* BlueZ version (`bluetoothctl -v`) in case of Linux: N/A

### Description

I am trying to read the "Device Name" characteristic by connecting to the device and using `read_gatt_char`. The Generic Access Profile is present when I inspect the device with LightBlue

I am receiving:
bleak.exc.BleakError: Characteristic 00002a00-0000-1000-8000-00805f9b34fb was not found!

And the service is not being discovered:
```
Connected: True
0000180a-0000-1000-8000-00805f9b34fb (Handle: 14): Device Information
00001818-0000-1000-8000-00805f9b34fb (Handle: 37): Cycling Power
00001826-0000-1000-8000-00805f9b34fb (Handle: 51): Fitness Machine
0000181c-0000-1000-8000-00805f9b34fb (Handle: 70): User Data
```

### What I Did

```
async def main(address):
    async with BleakClient(address) as client:
        print(f"Connected: {client.is_connected}")
        for x in client.services:
            print(x)
        test = await client.read_gatt_char('00002a00-0000-1000-8000-00805f9b34fb')
```

### Logs
```
    test = await client.read_gatt_char('00002a00-0000-1000-8000-00805f9b34fb')
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/corebluetooth/client.py", line 237, in read_gatt_char
    raise BleakError("Characteristic {} was not found!".format(char_specifier))
bleak.exc.BleakError: Characteristic 00002a00-0000-1000-8000-00805f9b34fb was not found!
```

**Comment by dlech** [comment]
Also see https://github.com/hbldh/bleak/issues/849#issuecomment-1255370264 (the part about adding a dedicate property to get the device name).
