### ISSUE TITLE
Program works on windows but not on linux

### ISSUE THREAD

**Issue by zapta** [hbldh/bleak#1226]
bleak version: 0.19.5
Python version: 3.10.6
Operating System: Ubuntu 22.04.1 LTS
BlueZ version (bluetoothctl -v) in case of Linux: bluetoothctl: 5.64

### Description

I have a test program that works on windows but fails on linux. The program writes two bytes to a characteristic, but the device returns and error to the write from linux and returns OK to the write from winodws. Comparing the write packets between the two shows a difference which likely causes to the failure with linux.

![packets](https://user-images.githubusercontent.com/2184769/219715362-49367f66-6602-4e90-a15a-4edd8a42e103.jpg)

I don't know what that flag is but it seems to specify a different kind of request.

### What I Did

Test program
```
import asyncio
import platform
import sys
import time
import signal
from bleak import BleakClient, BleakScanner
import signal




# Adapt to your actual device.
device_address = "0C:8B:95:F2:B4:36"

signal.signal(signal.SIGINT, lambda number, frame: sys.exit())

print(f"OS: {platform.platform()}", flush=True)
print(f"Platform:: {platform.uname()}", flush=True)
print(f"Python {sys.version}", flush=True)

async def test():
    print(f"Trying to connect to {device_address}", flush=True)
    device = await BleakScanner.find_device_by_address(device_address, timeout=10.0)
    assert device
    async with BleakClient(device) as client:
        assert client.is_connected
        print(f"Connected", flush=True)
        service = client.services.get_service("6b6a78d7-8ee0-4a26-ba7b-62e357dd9720")
        assert(service)
        print(f"Found service", flush=True)
        chrc = service.get_characteristic("ff06")
        assert(chrc)
        print(f"Found characteristic", flush=True)
        while True:
          print(f"Sending command", flush=True)
          await client.write_gatt_char(chrc, bytearray([0x03, 0x05]))
          await asyncio.sleep(3)

asyncio.run(test())
```

### Logs and packets

[linux_log.txt](https://github.com/hbldh/bleak/files/10769020/linux_log.txt)
[windows_log.txt](https://github.com/hbldh/bleak/files/10769021/windows_log.txt)
[linux_packets.zip](https://github.com/hbldh/bleak/files/10769022/linux_packets.zip)
[windows_packets.zip](https://github.com/hbldh/bleak/files/10769023/windows_packets.zip)

**Comment by dlech** [comment]
![image](https://user-images.githubusercontent.com/963645/219720090-f39304ef-9200-447d-b4e5-cf248c5a9b40.png)

According to the packet capture the "ff06" characteristic only support Write and not Write Without Response, so you need to add `response=True` to the call to `write_gatt_char()`.

**Comment by zapta** [comment]
Thanks @dlech, I changed the device firmware to declare the characteristic as ESP_GATT_CHAR_PROP_BIT_WRITE_NR instead of ESP_GATT_CHAR_PROP_BIT_WRITE and it works now, so I am good.

You may want to look why the windows and linux version have different behaviors but this may be in the underlying stacks. Linux does consider the declaration of the charateristic and windows doesn't.

**Comment by dlech** [comment]
I'm going to go ahead and close this one since it is working now and we have #909 to improve the default situation.
