### ISSUE TITLE
Question about BLEBridge dll vs pythonnet

### ISSUE THREAD

**Issue by Alex-EEE** [hbldh/bleak#123]
Was going to try using pythonnet to access the Windows BLE api directly ( I'm trying to debug something that another team is seeing in C#, so I want to be very close to the same API calls they're using )  I notice you guys mix calls to pythonnet alongside that DLL you created ( Bridge ).  Is there a pitfall in calling the Windows BLE API with pythonnet?  Why the DLL wrapper mixed with pythonnet?

**Comment by hbldh** [comment]
A reasonable question. The short answer is that I do not know why it is needed exactly, but I have been uanble to make Bleak work without it as of yet.

As you can see [here](https://github.com/hbldh/bleak/blob/master/BleakUWPBridge/BleakUWPBridge/Bridge.cs), the wrapper does not contain much at all. Current problems:
- I have been unable to deregister notification/handlers through `pythonnet`, something that is critical to proper functioning. A `char.ValueChanged -= my_function` in Python does not seem to work with the Windows namespace objects.
- Also, without it I have been unable to get any `import` from the `Windows` namespace to work in Python. The critical part of the bridge to get this to work is [this](https://github.com/hbldh/bleak/blob/master/BleakUWPBridge/BleakUWPBridge/BleakUWPBridge.csproj#L113-L117). This package needs to be included, and if I upgrade it the bridge won't work as before.
- If I remove the [`DummyMethod`](https://github.com/hbldh/bleak/blob/master/BleakUWPBridge/BleakUWPBridge/Bridge.cs#L40-L44) the `Windows` namespace cannot be imported. It seems to have something to do with it being asynchronous, but I have no idea what.

This construction is brittle and undesired, but it works and I have not had time to revisit this and improve it.
