### ISSUE TITLE
Race condition in BleakScannerWinRT.stop

### ISSUE THREAD

**Issue by rtoijala** [hbldh/bleak#1249]
* bleak version: latest commit (https://github.com/hbldh/bleak/commit/eb48a90b0ac88e67b12f9f9f6de182a3ea971ac3)
* Python version: 3.10.5
* Operating System: Windows 10 22H2 19045.2604
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

`BleakScannerWinRT` looks like this (I have added some debug logging which is shown here):
```python3
class BleakScannerWinRT(self, sender, e):
    def _stopped_handler(self, sender, e):
        if not self.watcher:
            logger.error("_stopped_handler: watcher is None")
        logger.debug(
            "{0} devices found. Watcher status: {1}.".format(
                len(self.seen_devices), self.watcher.status
            )
        )
        self._stopped_event.set()

    async def start(self) -> None:
        ...
        self._received_token = self.watcher.add_received(
            lambda s, e: [logger.debug("watcher.received"), event_loop.call_soon_threadsafe(self._received_handler, s, e)][1]
        )
        self._stopped_token = self.watcher.add_stopped(
            lambda s, e: [logger.debug("watcher.stopped"), event_loop.call_soon_threadsafe(self._stopped_handler, s, e)][1]
        )
        ...

    async def stop(self):
        logger.debug("scanner.stop, status is {0}".format(self.watcher.status))
        self.watcher.stop()

        if self.watcher.status == BluetoothLEAdvertisementWatcherStatus.STOPPING:
            await self._stopped_event.wait()
        else:
            logger.debug(
                "skipping waiting for stop because status is %s",
                self.watcher.status.name,
            )

        ...

        self.watcher = None
        logger.debug("watcher = None")
```

 `self.watcher.status` can become `BluetoothLEAdvertisementWatcherStatus.STOPPED` before `_stopped_handler` is called. If it is set to `STOPPED` also before the check in `stop`, `stop` skips the wait and can finish and set `watcher = None` before `_stopped_handler` is called. `stopped_handler` then tries to access the `status` attribute on `self.watcher`, which is `None`, leading to an `AttributeError`.

See the log snipper below.

### What I Did

I an infinite loop, I call `devices = await bleak.BleakScanner.discover(timeout=3)`, connect to one of the devices, write one GATT characteristic, and disconnect. I think the connect/write/disconnect part is likely unnecessary for reproducing this error.

The error pops up around 3 times per 100 iterations. I think it occurs more often when not enabling debug logging but have not done the statistics.

Relevant part of the logs:
```
2023-03-06 13:48:11,147 bleak.backends.winrt.scanner Dummy-3 DEBUG: watcher.received
2023-03-06 13:48:11,148 bleak.backends.winrt.scanner MainThread DEBUG: Received XX:XX:XX:XX:XX:XX .
2023-03-06 13:48:11,291 bleak.backends.winrt.scanner MainThread DEBUG: scanner.stop, status is 1
2023-03-06 13:48:11,293 bleak.backends.winrt.scanner MainThread DEBUG: skipping waiting for stop because status is STOPPED
2023-03-06 13:48:11,294 bleak.backends.winrt.scanner MainThread DEBUG: watcher = None
Here my app prints something after `BleakScanner.discover(timeout=3)` finishes.
2023-03-06 13:48:11,294 bleak.backends.winrt.scanner Dummy-3 DEBUG: watcher.stopped
2023-03-06 13:48:11,296 bleak.backends.winrt.scanner MainThread ERROR: _stopped_handler: watcher is None
Exception in callback BleakScannerWinRT._stopped_handler(<_bleak_winrt...001F44757BCD0>, <_bleak_winrt...001F44757BE70>)
handle: <Handle BleakScannerWinRT._stopped_handler(<_bleak_winrt...001F44757BCD0>, <_bleak_winrt...001F44757BE70>)>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bleak\backends\winrt\scanner.py", line 215, in _stopped_handler
    len(self.seen_devices), self.watcher.status
AttributeError: 'NoneType' object has no attribute 'status'
```

The line number in the traceback is slightly off from the commit mentioned above because of the additional debug prints.
`status == 1` means [`STARTED`](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcherstatus?view=winrt-19041). `status == 3` means `STOPPED`.

### Logs

No more logs, sorry, since they contain confidential device names.

**Comment by dlech** [comment]
Should be fixed by #1331
