### ISSUE TITLE
'NoneType' object has no attribute 'max_pdu_size' -- again.

### ISSUE THREAD

**Issue by joooeey** [hbldh/bleak#1253]
* bleak version: 0.19.5
* Python version: 3.10.9
* Operating System: Windows 10
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

I was trying to connect to two BLE devices. My code sometimes works and sometimes I get an error where bleak tries to get `.max_pdu_size` from a name that refers to `None`. Both 0.17.0 and 0.19.0 supposedly fixed similar errors but it still happens.

### What I Did

I only have a mix of printouts and a traceback for now:

```
Connecting to sensorbox ...
Connecting to controller ...
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<BleakClientWinRT.get_services() done, defined at C:\Users\user\anaconda3\envs\moma\lib\site-packages\bleak\backends\winrt\client.py:601> exception=AttributeError("'NoneType' object has no attribute 'max_pdu_size'")>
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\moma\lib\site-packages\bleak\backends\winrt\client.py", line 667, in get_services
    characteristic, self._session.max_pdu_size - 3
AttributeError: 'NoneType' object has no attribute 'max_pdu_size'
TimeoutError()
sensorbox not connected.
Connecting to sensorbox ...
```

From the trace and my code I can figure out that issue happens at

```
async with BleakClient(
            uuid,
            disconnected_callback=lambda _: asyncio_event.set,
        ) as client:
```

**Comment by dlech** [comment]
Is this still a problem if you use the latest `develop` branch?

**Comment by joooeey** [comment]
> Is this still a problem if you use the latest `develop` branch?

No, it appears to be resolved. I'll report if it happens again.

When is the next release?

**Comment by dlech** [comment]
Don't have an ETA, but hopefully soon.
