### ISSUE TITLE
crashed at start

### ISSUE THREAD

**Issue by littleningmeng** [hbldh/bleak#1266]
* bleak version: 0.20.1
* Python version: 3.10.8
* Operating System: MacOS(13.0.1 (22A400)) on Apple M1 Pro

### Description

crashed at start!  

### What I Did
just try the demo code. 
```python
import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

### Logs
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [51035]
Path:                  /opt/homebrew/*/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.10.8 (3.10.8)
Code Type:             ARM-64 (Native)
Parent Process:        zsh [41496]
Responsible:           iTerm2 [41484]
User ID:               501

Date/Time:             2023-03-25 13:44:35.4493 +0800
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Anonymous UUID:        DC13B28B-1A9D-7285-EF95-04440AAFC1B5

Sleep/Wake UUID:       B1AFC9BD-1685-4CF6-A8C2-CD55DD142AC5

Time Awake Since Boot: 7000 seconds
Time Since Wake:       2490 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1884365e4 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x188472638 _pthread_cond_wait + 1232
2   Python                        	       0x105234134 PyThread_acquire_lock_timed + 372
3   Python                        	       0x105294140 acquire_timed + 232
4   Python                        	       0x105294308 lock_PyThread_acquire_lock + 56
5   Python                        	       0x1050ea57c method_vectorcall_VARARGS_KEYWORDS + 156
6   Python                        	       0x1051d6ee4 call_function + 128
7   Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
8   Python                        	       0x1051c8ddc _PyEval_Vector + 376
9   Python                        	       0x1051d6ee4 call_function + 128
10  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
11  Python                        	       0x1051c8ddc _PyEval_Vector + 376
12  Python                        	       0x1051d6ee4 call_function + 128
13  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
14  Python                        	       0x1051c8ddc _PyEval_Vector + 376
15  _objc.cpython-310-darwin.so   	       0x105d623fc pysel_vectorcall + 532
16  Python                        	       0x1051d6ee4 call_function + 128
17  Python                        	       0x1051d46fc _PyEval_EvalFrameDefault + 42688
18  Python                        	       0x1051c8ddc _PyEval_Vector + 376
19  Python                        	       0x1050dd690 _PyObject_FastCallDictTstate + 208
20  Python                        	       0x105152fe4 slot_tp_init + 196
21  Python                        	       0x10514b020 type_call + 288
22  Python                        	       0x1050dddd8 _PyObject_Call + 128
23  Python                        	       0x1051d48c4 _PyEval_EvalFrameDefault + 43144
24  Python                        	       0x1051c8ddc _PyEval_Vector + 376
25  Python                        	       0x1050dd620 _PyObject_FastCallDictTstate + 96
26  Python                        	       0x105152fe4 slot_tp_init + 196
27  Python                        	       0x10514b020 type_call + 288
28  Python                        	       0x1050dddd8 _PyObject_Call + 128
29  Python                        	       0x1051d48c4 _PyEval_EvalFrameDefault + 43144
30  Python                        	       0x1050f3c6c gen_send_ex2 + 224
31  Python                        	       0x1051ce534 _PyEval_EvalFrameDefault + 17656
32  Python                        	       0x1050f3c6c gen_send_ex2 + 224
33  _asyncio.cpython-310-darwin.so	       0x1055e8a4c task_step_impl + 440
34  _asyncio.cpython-310-darwin.so	       0x1055e8820 task_step + 52
35  Python                        	       0x1050dd3b8 _PyObject_MakeTpCall + 136
36  Python                        	       0x1051ecf9c context_run + 92
37  Python                        	       0x10512f318 cfunction_vectorcall_FASTCALL_KEYWORDS + 84
38  Python                        	       0x1051d48c4 _PyEval_EvalFrameDefault + 43144
39  Python                        	       0x1051c8ddc _PyEval_Vector + 376
40  Python                        	       0x1051d6ee4 call_function + 128
41  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
42  Python                        	       0x1051c8ddc _PyEval_Vector + 376
43  Python                        	       0x1051d6ee4 call_function + 128
44  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
45  Python                        	       0x1051c8ddc _PyEval_Vector + 376
46  Python                        	       0x1051d6ee4 call_function + 128
47  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
48  Python                        	       0x1051c8ddc _PyEval_Vector + 376
49  Python                        	       0x1051d6ee4 call_function + 128
50  Python                        	       0x1051d4684 _PyEval_EvalFrameDefault + 42568
51  Python                        	       0x1051c8ddc _PyEval_Vector + 376
52  Python                        	       0x1051d6ee4 call_function + 128
53  Python                        	       0x1051d46fc _PyEval_EvalFrameDefault + 42688
54  Python                        	       0x1051c8ddc _PyEval_Vector + 376
55  Python                        	       0x1051c8c50 PyEval_EvalCode + 104
56  Python                        	       0x105223304 run_eval_code_obj + 84
57  Python                        	       0x105223268 run_mod + 112
58  Python                        	       0x105222efc pyrun_file + 148
59  Python                        	       0x105222830 _PyRun_SimpleFileObject + 268
60  Python                        	       0x105221e74 _PyRun_AnyFileObject + 232
61  Python                        	       0x105244ee8 pymain_run_file_obj + 220
62  Python                        	       0x105244638 pymain_run_file + 72
63  Python                        	       0x105243ec8 Py_RunMain + 872
64  Python                        	       0x1052452c4 Py_BytesMain + 40
65  dyld                          	       0x188147e50 start + 2544

Thread 1:
0   libsystem_pthread.dylib       	       0x18846ce18 start_wqthread + 0

Thread 2 Crashed::  Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib        	       0x18843f76c __abort_with_payload + 8
1   libsystem_kernel.dylib        	       0x188463e68 abort_with_payload_wrapper_internal + 104
2   libsystem_kernel.dylib        	       0x188463e9c abort_with_payload + 16
3   TCC                           	       0x18d12486c __TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__ + 172
4   TCC                           	       0x18d125184 __TCCAccessRequest_block_invoke.197 + 588
5   TCC                           	       0x18d122624 __tccd_send_message_block_invoke + 632
6   libxpc.dylib                  	       0x1881e1670 _xpc_connection_reply_callout + 124
7   libxpc.dylib                  	       0x1881e1560 _xpc_connection_call_reply_async + 88
8   libdispatch.dylib             	       0x1882eb584 _dispatch_client_callout3 + 20
9   libdispatch.dylib             	       0x188309710 _dispatch_mach_msg_async_reply_invoke + 344
10  libdispatch.dylib             	       0x1882fdd08 _dispatch_kevent_worker_thread + 1280
11  libsystem_pthread.dylib       	       0x18846e138 _pthread_wqthread + 344
12  libsystem_pthread.dylib       	       0x18846ce20 start_wqthread + 8

Thread 2 crashed with ARM Thread State (64-bit):
    x0: 0x000000000000000b   x1: 0x0000000000000000   x2: 0x000000013d69a0a0   x3: 0x0000000000000022
    x4: 0x000000013d69a0d4   x5: 0x0000000000000000   x6: 0x00fb000004220122   x7: 0x0000000000000001
    x8: 0x0000000000000020   x9: 0x103740af4db5004c  x10: 0x0100000100000000  x11: 0x000000000002e272
   x12: 0x00000010001a57b6  x13: 0x0000000000000000  x14: 0x0000020000011000  x15: 0x0000000100000000
   x16: 0x0000000000000209  x17: 0x00000001e897e900  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000013d69a0d4  x21: 0x0000000000000022  x22: 0x000000013d69a0a0  x23: 0x0000000000000000
   x24: 0x000000000000000b  x25: 0x0000600001dec240  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b2a2630   lr: 0x0000000188463e68
    sp: 0x000000016b2a25f0   pc: 0x000000018843f76c cpsr: 0x40001000
   far: 0x0000000156810208  esr: 0x56000080  Address size fault

Binary Images:
       0x188432000 -        0x18846affb libsystem_kernel.dylib (*) <6d6644d3-3db3-34c4-b1e3-c675ec5360f0> /usr/lib/system/libsystem_kernel.dylib
       0x18846b000 -        0x188477ffb libsystem_pthread.dylib (*) <886caca0-5762-3640-8db2-3fa3b911c062> /usr/lib/system/libsystem_pthread.dylib
       0x105074000 -        0x105347fff org.python.python (3.10.8, (c) 2001-2021 Python Software Foundation.) <ee96e2f7-d454-3fdb-b251-2d5245854092> /opt/homebrew/*/Python.framework/Versions/3.10/Python
       0x105ce4000 -        0x105d83fff _objc.cpython-310-darwin.so (*) <e477097d-4cf0-3b7b-ab8d-ffc93939cc59> /opt/homebrew/*/_objc.cpython-310-darwin.so
       0x1055e4000 -        0x1055ebfff _asyncio.cpython-310-darwin.so (*) <1fa80b3f-7492-3296-8223-eb9377cd7285> /opt/homebrew/*/Python.framework/Versions/3.10/lib/python3.10/lib-dynload/_asyncio.cpython-310-darwin.so
       0x188142000 -        0x1881cc4bf dyld (*) <de46dd52-4994-3fd8-b4b4-e352a1a19354> /usr/lib/dyld
       0x18d11f000 -        0x18d13cff5 com.apple.TCC (1.0) <5c061817-4ef1-31e2-be46-a9a1320cd93f> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
       0x1881d2000 -        0x188214fff libxpc.dylib (*) <44992a1e-d222-3d40-841d-e2cf9e26f67e> /usr/lib/system/libxpc.dylib
       0x1882e7000 -        0x18832efff libdispatch.dylib (*) <40c9c98c-00d6-3e8e-9ad3-2ed6cf0d0cfe> /usr/lib/system/libdispatch.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 452
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=872.0M resident=0K(0%) swapped_out_or_unallocated=872.0M(100%)
Writable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           196.2M       21 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                         48K        3 
Stack                             17.1M        3 
VM_ALLOCATE                       12.0M       13 
__AUTH                             312K       62 
__AUTH_CONST                      3676K      149 
__DATA                            2345K      179 
__DATA_CONST                      5096K      189 
__DATA_DIRTY                       373K       60 
__LINKEDIT                       764.4M       40 
__OBJC_CONST                       313K       39 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1981K        1 
__TEXT                           107.5M      197 
dyld private memory                256K        1 
mapped file                       29.1M        4 
shared memory                       64K        4 
===========                     =======  ======= 
TOTAL                              2.0G      978 
TOTAL, minus reserved VM space     1.2G      978 

-----------
Full Report
-----------

{"app_name":"Python","timestamp":"2023-03-25 13:44:35.00 +0800","app_version":"3.10.8","slice_uuid":"7a60069e-0b4f-37dc-8f02-bda4bfe905f2","build_version":"3.10.8","platform":1,"bundleID":"org.python.python","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0.1 (22A400)","roots_installed":0,"name":"Python","incident_id":"6B7D6BCE-9826-4828-8EBB-6FCD3CAC4533"}
{
  "uptime" : 7000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 1951,
  "osVersion" : {
    "train" : "macOS 13.0.1",
    "build" : "22A400",
    "releaseType" : "User"
  },
  "captureTime" : "2023-03-25 13:44:35.4493 +0800",
  "incident" : "6B7D6BCE-9826-4828-8EBB-6FCD3CAC4533",
  "pid" : 51035,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-03-25 13:44:35.3135 +0800",
  "procStartAbsTime" : 170244705211,
  "procExitAbsTime" : 170247955927,
  "procName" : "Python",
  "procPath" : "\/opt\/homebrew\/*\/Python.framework\/Versions\/3.10\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "bundleInfo" : {"CFBundleShortVersionString":"3.10.8","CFBundleVersion":"3.10.8","CFBundleIdentifier":"org.python.python"},
  "storeInfo" : {"deviceIdentifierForVendor":"34033F27-4487-561C-8EA6-CA45034100D9","thirdParty":true},
  "parentProc" : "zsh",
  "parentPid" : 41496,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "DC13B28B-1A9D-7285-EF95-04440AAFC1B5",
  "responsiblePid" : 41484,
  "responsibleProc" : "iTerm2",
  "wakeTime" : 2490,
  "sleepWakeUUID" : "B1AFC9BD-1685-4CF6-A8C2-CD55DD142AC5",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":518,"code":0,"namespace":"TCC","details":["This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data."]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":452},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 2,
  "threads" : [{"id":189039,"queue":"com.apple.main-thread","frames":[{"imageOffset":17892,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":30264,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":1835316,"symbol":"PyThread_acquire_lock_timed","symbolLocation":372,"imageIndex":2},{"imageOffset":2228544,"symbol":"acquire_timed","symbolLocation":232,"imageIndex":2},{"imageOffset":2229000,"symbol":"lock_PyThread_acquire_lock","symbolLocation":56,"imageIndex":2},{"imageOffset":484732,"symbol":"method_vectorcall_VARARGS_KEYWORDS","symbolLocation":156,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":517116,"symbol":"pysel_vectorcall","symbolLocation":532,"imageIndex":3},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443580,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42688,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":431760,"symbol":"_PyObject_FastCallDictTstate","symbolLocation":208,"imageIndex":2},{"imageOffset":913380,"symbol":"slot_tp_init","symbolLocation":196,"imageIndex":2},{"imageOffset":880672,"symbol":"type_call","symbolLocation":288,"imageIndex":2},{"imageOffset":433624,"symbol":"_PyObject_Call","symbolLocation":128,"imageIndex":2},{"imageOffset":1444036,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":43144,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":431648,"symbol":"_PyObject_FastCallDictTstate","symbolLocation":96,"imageIndex":2},{"imageOffset":913380,"symbol":"slot_tp_init","symbolLocation":196,"imageIndex":2},{"imageOffset":880672,"symbol":"type_call","symbolLocation":288,"imageIndex":2},{"imageOffset":433624,"symbol":"_PyObject_Call","symbolLocation":128,"imageIndex":2},{"imageOffset":1444036,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":43144,"imageIndex":2},{"imageOffset":523372,"symbol":"gen_send_ex2","symbolLocation":224,"imageIndex":2},{"imageOffset":1418548,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":17656,"imageIndex":2},{"imageOffset":523372,"symbol":"gen_send_ex2","symbolLocation":224,"imageIndex":2},{"imageOffset":19020,"symbol":"task_step_impl","symbolLocation":440,"imageIndex":4},{"imageOffset":18464,"symbol":"task_step","symbolLocation":52,"imageIndex":4},{"imageOffset":431032,"symbol":"_PyObject_MakeTpCall","symbolLocation":136,"imageIndex":2},{"imageOffset":1544092,"symbol":"context_run","symbolLocation":92,"imageIndex":2},{"imageOffset":766744,"symbol":"cfunction_vectorcall_FASTCALL_KEYWORDS","symbolLocation":84,"imageIndex":2},{"imageOffset":1444036,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":43144,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443460,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42568,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1453796,"symbol":"call_function","symbolLocation":128,"imageIndex":2},{"imageOffset":1443580,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":42688,"imageIndex":2},{"imageOffset":1396188,"symbol":"_PyEval_Vector","symbolLocation":376,"imageIndex":2},{"imageOffset":1395792,"symbol":"PyEval_EvalCode","symbolLocation":104,"imageIndex":2},{"imageOffset":1766148,"symbol":"run_eval_code_obj","symbolLocation":84,"imageIndex":2},{"imageOffset":1765992,"symbol":"run_mod","symbolLocation":112,"imageIndex":2},{"imageOffset":1765116,"symbol":"pyrun_file","symbolLocation":148,"imageIndex":2},{"imageOffset":1763376,"symbol":"_PyRun_SimpleFileObject","symbolLocation":268,"imageIndex":2},{"imageOffset":1760884,"symbol":"_PyRun_AnyFileObject","symbolLocation":232,"imageIndex":2},{"imageOffset":1904360,"symbol":"pymain_run_file_obj","symbolLocation":220,"imageIndex":2},{"imageOffset":1902136,"symbol":"pymain_run_file","symbolLocation":72,"imageIndex":2},{"imageOffset":1900232,"symbol":"Py_RunMain","symbolLocation":872,"imageIndex":2},{"imageOffset":1905348,"symbol":"Py_BytesMain","symbolLocation":40,"imageIndex":2},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":5}]},{"id":189041,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"triggered":true,"id":189042,"threadState":{"x":[{"value":11},{"value":0},{"value":5325299872},{"value":34},{"value":5325299924},{"value":0},{"value":70650219223712034},{"value":1},{"value":32},{"value":1168473749993095244},{"value":72057598332895232},{"value":189042},{"value":68721203126},{"value":0},{"value":2199023325184},{"value":4294967296},{"value":521},{"value":8197236992},{"value":0},{"value":0},{"value":5325299924},{"value":34},{"value":5325299872},{"value":0},{"value":11},{"value":105553147642432},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6581272168},"cpsr":{"value":1073745920},"fp":{"value":6092891696},"sp":{"value":6092891632},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6581122924,"matchesCrashFrame":1},"far":{"value":5746262536}},"queue":"com.apple.root.default-qos","frames":[{"imageOffset":55148,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":204392,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":204444,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":22636,"symbol":"__TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__","symbolLocation":172,"imageIndex":6},{"imageOffset":24964,"symbol":"__TCCAccessRequest_block_invoke.197","symbolLocation":588,"imageIndex":6},{"imageOffset":13860,"symbol":"__tccd_send_message_block_invoke","symbolLocation":632,"imageIndex":6},{"imageOffset":63088,"symbol":"_xpc_connection_reply_callout","symbolLocation":124,"imageIndex":7},{"imageOffset":62816,"symbol":"_xpc_connection_call_reply_async","symbolLocation":88,"imageIndex":7},{"imageOffset":17796,"symbol":"_dispatch_client_callout3","symbolLocation":20,"imageIndex":8},{"imageOffset":141072,"symbol":"_dispatch_mach_msg_async_reply_invoke","symbolLocation":344,"imageIndex":8},{"imageOffset":93448,"symbol":"_dispatch_kevent_worker_thread","symbolLocation":1280,"imageIndex":8},{"imageOffset":12600,"symbol":"_pthread_wqthread","symbolLocation":344,"imageIndex":1},{"imageOffset":7712,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6581067776,
    "size" : 233468,
    "uuid" : "6d6644d3-3db3-34c4-b1e3-c675ec5360f0",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6581301248,
    "size" : 53244,
    "uuid" : "886caca0-5762-3640-8db2-3fa3b911c062",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4379328512,
    "CFBundleShortVersionString" : "3.10.8, (c) 2001-2021 Python Software Foundation.",
    "CFBundleIdentifier" : "org.python.python",
    "size" : 2965504,
    "uuid" : "ee96e2f7-d454-3fdb-b251-2d5245854092",
    "path" : "\/opt\/homebrew\/*\/Python.framework\/Versions\/3.10\/Python",
    "name" : "Python",
    "CFBundleVersion" : "3.10.8"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4392370176,
    "size" : 655360,
    "uuid" : "e477097d-4cf0-3b7b-ab8d-ffc93939cc59",
    "path" : "\/opt\/homebrew\/*\/_objc.cpython-310-darwin.so",
    "name" : "_objc.cpython-310-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4385030144,
    "size" : 32768,
    "uuid" : "1fa80b3f-7492-3296-8223-eb9377cd7285",
    "path" : "\/opt\/homebrew\/*\/Python.framework\/Versions\/3.10\/lib\/python3.10\/lib-dynload\/_asyncio.cpython-310-darwin.so",
    "name" : "_asyncio.cpython-310-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6577987584,
    "size" : 566464,
    "uuid" : "de46dd52-4994-3fd8-b4b4-e352a1a19354",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6661730304,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.TCC",
    "size" : 122870,
    "uuid" : "5c061817-4ef1-31e2-be46-a9a1320cd93f",
    "path" : "\/System\/Library\/PrivateFrameworks\/TCC.framework\/Versions\/A\/TCC",
    "name" : "TCC",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6578577408,
    "size" : 274432,
    "uuid" : "44992a1e-d222-3d40-841d-e2cf9e26f67e",
    "path" : "\/usr\/lib\/system\/libxpc.dylib",
    "name" : "libxpc.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6579712000,
    "size" : 294912,
    "uuid" : "40c9c98c-00d6-3e8e-9ad3-2ed6cf0d0cfe",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  }
],
  "sharedCache" : {
  "base" : 6577340416,
  "size" : 3403612160,
  "uuid" : "2d053604-1cb6-3821-a8df-360eb2eb519b"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=872.0M resident=0K(0%) swapped_out_or_unallocated=872.0M(100%)\nWritable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           196.2M       21 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                         48K        3 \nStack                             17.1M        3 \nVM_ALLOCATE                       12.0M       13 \n__AUTH                             312K       62 \n__AUTH_CONST                      3676K      149 \n__DATA                            2345K      179 \n__DATA_CONST                      5096K      189 \n__DATA_DIRTY                       373K       60 \n__LINKEDIT                       764.4M       40 \n__OBJC_CONST                       313K       39 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1981K        1 \n__TEXT                           107.5M      197 \ndyld private memory                256K        1 \nmapped file                       29.1M        4 \nshared memory                       64K        4 \n===========                     =======  ======= \nTOTAL                              2.0G      978 \nTOTAL, minus reserved VM space     1.2G      978 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.root.default-qos"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6406610c03b3136e9aacb1ab",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000663
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 8419.41.10, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: AX88179A
USB Device: USB2.0 HUB
USB Device: USB2.1 Hub
USB Device: USB C Video Adaptor
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Comment by dlech** [comment]
Please see https://bleak.readthedocs.io/en/latest/troubleshooting.html#bleak-crashes-with-sigabrt-on-macos
