### ISSUE TITLE
Add support for adapter selection in Windows

### ISSUE THREAD

**Issue by eranzim** [hbldh/bleak#1299]
* bleak version: master
* Python version: all
* Operating System: Windows

### Description

bluezdbus supports passing the adapter to use as parameter (e.g. https://github.com/hbldh/bleak/pull/524). Winrt doesn't. Would it be possible to add this support for Windows as well?
Thanks!

**Comment by dlech** [comment]
Windows only allows a single adapter at the driver level. If you have two adapters and open the *Device Manager*, you will see one has a :warning: icon and is not being used. To use a specific adapter, you have to disable all others in the *Device Manager*. This can't be done without administrative privileges, so is is not something that can be done in Bleak.
