### ISSUE TITLE
BLE MAC address on MacOS instead of system ID

### ISSUE THREAD

**Issue by 5frank** [hbldh/bleak#140]
* bleak: 0.5.1
* os: Darwin-18.7.0-x86_64-i386-64bit
* python: 3.7.5

Perhaps it is only me, but it would be nice if the CoreBluetooth backend used BLE MAC address and not the system "device UUID"? It would make my scripts and configurations portable (I am usually on Linux).
I made an attempt to implement this inspired from [noble](https://github.com/noble/noble). Initial tests seems to work even if the solution feels somewhat hacky.

Question:
1. Do anyone see any problems with this method of obtaining the address (i.e. read the "CoreBluetoothCache" from `/Library/Preferences/com.apple.Bluetooth.plist`)? Is there a better way?

2. It seems the reason MacOS uses UUID is because some security feature in BLE that hides the MAC address. Does anyone know how this is handled on Windows and Linux/BlueZ?

3. Is it a bad or good idea to accept both MacOS "device UUID" and BLE MAC address? Would make this change backward compatible, but not sure if anyone cares. 

example how to read `CoreBluetoothCache`:
```python
from plistlib import load as plist_load
async def __get_addr_from_CoreBluetoothCache():
    ''' returns dict {MacOS_device_UUID : BLE_MAC_address } '''

    path = "/Library/Preferences/com.apple.Bluetooth.plist"
    try:
        with open(path, "rb") as f:
            plist = plist_load(f)
    except FileNotFoundError:
        logger.warning("{} do not exist".format(path))
        return {}

    if "CoreBluetoothCache" not in plist:
        logger.debug("No CoreBluetoothCache in {}".format(path))
        return {}

    cbcache = plist["CoreBluetoothCache"]  

    if cbcache is None:
        return {}

    uuid_to_addr = {}

    for devuuid, devinfo in cbcache.items():
        if "DeviceAddress" not in devinfo:
            continue

        addr = devinfo["DeviceAddress"]
        addr = addr.replace('-', ':')

        uuid_to_addr[devuuid] = addr

    return uuid_to_addr 
```

**Comment by 5frank** [comment]
1. It seems that CoreBluetoothCache is only updated after a connect. So you still need the UUID or some other workaround.

3. Could possible check whatever the "address" passed to `connect` is a 128-bit UUID or 48-bit MAC address an handle it accordingly. (assuming there is a sane way to obtain the MAC)

**Comment by hbldh** [comment]
From the Bleak documentation:
> The most noticible difference between the other backends of bleak and this backend, is that CoreBluetooth doesn’t scan for other devices via MAC address. Instead, UUIDs are utilized that are often unique between the device that is scanning the the device that is being scanned.

It would be nice to be able to use MAC address, but the effort to circumvent the macOS UUID solution is not proportional to the benefits. Reading from a cache file on disk is a reasonable idea, but I do not think it is reliable enough to be used for creating connections.

Bleak strives to have an identical API, but is accepting of OS specific differences. macOS discovers by UUID and connects by UUID, it would be counterproductive to force MAC connecting. This is one of the few "this we just have to accept" differences, in my eyes.

**Comment by hbldh** [comment]
I do not think this is solvable. Will close for now.

**Comment by dlech** [comment]
FYI, I have found a hack for this. See #1073. Give it a 👍 if this is still a needed feature.
