### ISSUE TITLE
Upgrade PyObjC to recent 10 release

### ISSUE THREAD

**Issue by daveisfera** [hbldh/bleak#1426]
* bleak version: 0.21.1
* Python version: 3.9.18
* Operating System: macOS 13.5.2
* BlueZ version (`bluetoothctl -v`) in case of Linux: N/A

### Description

PyObjC [released version 10](https://pyobjc.readthedocs.io/en/latest/changelog.html#version-10-0) so it would be good to upgrade to that for macOS 14 support

### What I Did

I can submit a PR to do this, if you'd like

### Logs

N/A

**Comment by dlech** [comment]
> I can submit a PR to do this, if you'd like

Yes please.
