### ISSUE TITLE
Difference Between scanner.ExtraArg.scanning_mode and BleakScanner(scanning_mode) 

### ISSUE THREAD

**Issue by alphonsekoh** [hbldh/bleak#1462]
* bleak version: 0.21.1
* Python version: 3.9.2
* Operating System: Debian 11 (Bullseye)
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.66

### Description

Passive scanning with these 2 methods yield different results 

### What I Did
I was trying to test for RSSI stability for my bluetooth beacons and used the BleakScanner for testing. 
I tried BleakScanner(scanning_mode="passive") with the or_pattern filters in my code: 
```python3
    async def init_and_scan(self):
        scanner = BleakScanner(
            self.simple_callback,
            scanning_mode="passive",
            bluez=BlueZScannerArgs(
                or_patterns=[
                    OrPattern(0, AdvertisementDataType.SERVICE_DATA_UUID16, b"\x6a\xfe")
                    OrPattern(0, AdvertisementDataType.MANUFACTURER_SPECIFIC_DATA, b"\x59\x00"),
                ]
            ),
        )
```

This code above gives me lesser scanning results compared to the code below when I changed the passive scanning as an ExtraArg. 

```python3
    async def init_and_scan(self):
        passive_filters = [OrPattern(0, AdvertisementDataType.SERVICE_DATA_UUID16, b"\x6a\xfe"),
                           OrPattern(0, AdvertisementDataType.MANUFACTURER_SPECIFIC_DATA, b"\x59\x00")]
        scanner = BleakScanner(detection_callback=self.simple_callback,
                               bluez=BlueZScannerArgs(or_patterns=passive_filters)
                               )
        scanner.ExtraArgs.scanning_mode = "passive"
```
May I know what is the difference between the 2 implementation? Does putting the scanning_mode in the constructor adds to the performance overheads and hence its slower? 

Thanks in advanced :)

**Comment by dlech** [comment]
`ExtraArgs` is for type hints only, so it should not be touched. As you saw, in order to get passive scanning, you have to pass it as an argument to `BleakScanner`.
