### ISSUE TITLE
Where can I download latest bleak Documentation pdf file?

### ISSUE THREAD

**Issue by snowuyl** [hbldh/bleak#1472]
* bleak version: v0.21.1
* Python version: v3.11.5
* Operating System: Windows 11

### Description
I have bleak Documentation v0.15.0a1 pdf file. But since the latest version of bleak is v0.21.1. Where can I download latest bleak Documentation pdf file?

**Comment by dlech** [comment]
This is something we will probably have to enable in the readthedocs config.

**Comment by snowuyl** [comment]
Thanks for your reply! Do you mean v0.15.0a1 is latest version of bleak Documentation PDF file?

**Comment by dlech** [comment]
it looks like we changed the config file in v0.17

**Comment by snowuyl** [comment]
Could I generate PDF document by myself?

**Comment by dlech** [comment]
sure, but I just fixed it so you can download a pdf from https://bleak.readthedocs.io/en/latest/ now

**Comment by snowuyl** [comment]
Thanks for your great support! I can download latest version of bleak PDF document.
