### ISSUE TITLE
I need to communicate with my ble Bluetooth device, but as long as my ble device is connected to the computer, it cannot be scanned. I can't scan using the computer's Bluetooth. How should I communicate in this situation? Thank you!

### ISSUE THREAD

**Issue by a37836323** [hbldh/bleak#1525]
I need to communicate with my ble Bluetooth device, but as long as my ble device is connected to the computer, it cannot be scanned. I can't scan using the computer's Bluetooth. How should I communicate in this situation? Thank you!

**Comment by dlech** [comment]
This feature is not implemented and has been requested in #367.

So closing this issue as a duplicate and if you have any further comments, please post them on the other issue.
