### ISSUE TITLE
Failed to connect: org.bluez.Error.Failed le-connection-abort-by-local

### ISSUE THREAD

**Issue by wahadatjan** [hbldh/bleak#1673]
* bleak version:0.22.2
* Python version: 3.11.6
* Operating System:Ubuntu 23.10
* BlueZ version (`bluetoothctl -v`) in case of Linux:5.68

### Description

I tried to connect the device using bleak program or using bluetoothctl i get the same issue that 
`Failed to connect: org.bluez.Error.Failed le-connection-abort-by-local` when i try to establish the connection .

**Comment by dlech** [comment]
If `bluetoothctl` can't connect, then Bleak can't either. 

The `le-connection-abort-by-local` is generally caused by RF interference, so if you can eliminate that, you might have a better chance at connecting. Also, using a different Bluetooth adapter could help.

**Comment by wahadatjan** [comment]
@dlech i was actually creating hotspot on Raspberry pi 
i disabled that and it worked.
Can you recommend any Bluetooth adapter which can handle multiple devices on Raspberry pi

**Comment by dlech** [comment]
Sorry, don't have much experience with that, so I don't have any recommendations.
