### ISSUE TITLE
Update RSSI of connected device

### ISSUE THREAD

**Issue by trivialkettle** [hbldh/bleak#1674]
* bleak version: 0.22
* Python version: 3.12
* Operating System: linux
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.78

### Description

I want to check the RSSI value of connected devices periodically, but the RSSI value is never updated.

### What I Did

After `discover()` I connect to a device and print `device.rssi` while the scanner is running in background

Did I miss one function to get the updated rssi value? If I am connected, my device does not send any Adv data anymore (since its already connected).

**Comment by dlech** [comment]
Related discussion: https://github.com/hbldh/bleak/discussions/879
