### ISSUE TITLE
How to identify source of notifications/indications when connected to multiple devices

### ISSUE THREAD

**Issue by kqkq** [hbldh/bleak#1695]
* bleak version: 0.22.3
* Python version: 3.9.6
* Operating System: macOS 15.1.1
* BlueZ version (`bluetoothctl -v`) in case of Linux: CoreBluetooth (macOS)

### Description

I connected to two identical BLE devices and `start_notify` for a Notification on both devices. I got callbacks from both devices correctly. But I cannot tell the source of the Notifications because both devices have the same Characteristics with the same Characteristic UUID & handle. The only difference between these devices is the `address` from a `BLEClient` object. However, the callback of `start_notify` only gives a `BleakGATTCharacteristic` object without a clue of the device address.

### What I Did

```
for dev in discovered_devices: # discovered_devices is a list of BLEDevice
    client = BleakClient(dev, disconnected_callback=disconnected_callback)
    await client.connect()
    def notify(sender, data):
        print(f"{sender}: {filename}") # Notifications from multiple devices mixed together
    await client.start_notify("ae3c", notify)
```

### Logs

Code above output logs like

```
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 12.BIN    #this is from device A
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 14.BIN    #this is from device A
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 13.BIN    #this is from device A
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 2.BIN        #this is from device B
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 3.BIN        #this is from device B
0000ae3c-0000-1000-8000-00805f9b34fb (Handle: 67): Vendor specific: 14.BIN    #this is from device A
```

Notifications from multiple devices mixed and have no way to distinguish

**Comment by dlech** [comment]
The usual solution is to use `functools.partial` to bind a device ID to the notification handler function before passing it to `start_notify()`.

**Comment by kqkq** [comment]
@dlech Thank you so much! It works well!

Closing this issue.
