### ISSUE TITLE
client.is_connected returns `True` even if the device is disconnected.

### ISSUE THREAD

**Issue by hardik-prajapati** [hbldh/bleak#185]
* bleak version: 0.6.1
* Python version: 3.7.4
* Operating System: Mas OS Mojave
* BlueZ version (`bluetoothctl -v`) in case of Linux: 

### Description

Device connected state is not properly maintained. 
```
connected = await self._client.is_connected()
```
`is_connected` returns `True` even if the device is disconnected.

Below are the logs:
```
connected: True
connected: True
2020-05-12 16:12:58,154 - bleak.backends.corebluetooth.CentralManagerDelegate - DEBUG - Peripheral Device disconnected!
connected: True
connected: True
```

### Solution
bleak/backends/corebluetooth/CentralManagerDelegate.py :
```
    def isConnected(self) -> bool:
        # Validate this
        return self.connected_peripheral != None
```
I think you should return `self._connection_state == CMDConnectionState.CONNECTED` instead of `self.connected_peripheral != None`

I can raise PR for this if you want.

Thanks, for the great library :) It is really useful.

**Comment by dlech** [comment]
Yes, please make a pull request if it fixes the problem.

**Comment by hbldh** [comment]
This is a valid point. Please make that PR.

**Comment by hardik-prajapati** [comment]
Created pull request here : https://github.com/hbldh/bleak/pull/187

**Comment by hbldh** [comment]
Merged the PR. Will close this when I make a new release. Thank you!
