### ISSUE TITLE
Tkinter askdirectory doesn't work when using bleak.

### ISSUE THREAD

**Issue by GitChris3004** [hbldh/bleak#205]
* bleak version: 0.6.4
* Python version: 3.7.4
* Operating System: Windows 10
* tkinter version: 8.6

### Description

Tkinter filedialog function askdirectory doesn't work in combination with bleak.

### What I Did
This code works without "import bleak". Otherwise it stuck without an error message.

```
import bleak
from tkinter.filedialog import askdirectory

file_path = askdirectory()
```

**Comment by hbldh** [comment]
I have no idea. Maybe it is a Tkinter problem? Bleak works without Tkinter and Tkinter works without Bleak.

Check this out and see if it can help you: https://stackoverflow.com/questions/47895765/use-asyncio-and-tkinter-or-another-gui-lib-together-without-freezing-the-gui

I have no idea why, and I will not guarantee that bleak will work with Tkinter. This is not an issue that I will look into.
