### ISSUE TITLE
Linux backend doc warning about event loops still true?

### ISSUE THREAD

**Issue by dhalbert** [hbldh/bleak#208]
[Documentation issue]

* bleak version: 0.6.4

`docs/backends/linux.rst` still says the below, but my impression is that this been fixed by #143 ?

> You should not create any new event loops when using Bleak with the BlueZ backend, only use the asyncio.get_event_loop. This is due to the way that the asyncioreactor is used right now.

> If more clients are needed, run these in separate processes right now, until a better recommendation is available.

**Comment by hbldh** [comment]
It has been fixed, but another error has popped up instead (the `[Errno 24] Too many open files.` in #169 and #171). You are right though, the documentation needs to be changed to describe the new situation instead. Thanks!
