### ISSUE TITLE
why does bleak set the logging level of the package instead of using whatever the caller sets?

### ISSUE THREAD

**Issue by danaronson** [hbldh/bleak#251]
* bleak version: latest
* Python version: n/a
* Operating System: n/a
* BlueZ version (`bluetoothctl -v`) in case of Linux: n/a

### Description

bleak sets the default logging level to DEBUG.  Although this can be overridden, is there some reason that it just doesn't use whatever the root logger is set to?

**Comment by hbldh** [comment]
Very good question. It is due to the fact that I wanted much logging when I developed and never got around to changing it. Will change this for the next release. Thank you for reporting it!
