### ISSUE TITLE
set_disconnected_callback have different behavior. works on Linux but crashes on MacOS.

### ISSUE THREAD

**Issue by 5frank** [hbldh/bleak#276]
* bleak version: 0.7.1
* Python version: 3.8.5
* Operating System: macOS-10.15.6
* BlueZ version (`bluetoothctl -v`) in case of Linux: 

### Description

`set_disconnected_callback` have different behavior on Linux and MacOS.

### What I Did

This works on Linux but crashes on MacOS.
```
    bleak_client.set_disconnected_callback(my_disconnect_callback)
    bleak_client.connect()
```
traceback:
```
  File "/usr/local/lib/python3.8/site-packages/bleak/backends/corebluetooth/client.py", line 111, in set_disconnected_callback
    manager = self._device_info.manager().delegate()
AttributeError: 'NoneType' object has no attribute 'manager'
```
(this as `manager` is None until connected.)
Changing the order (i.e. call `set_disconnected_callback` after `connect`) do not seem like a good solution as disconnect can occur before callback is set. Perhaps `set_disconnected_callback` could be deprecated  and replaced with a argument to either `BleakClient` or `BleakClient:connect()`? I suspect it would make it easier to handle this uniformly for all backends?

**Comment by hbldh** [comment]
I agree. Made a fix for it and will add it to 0.8.0 release. Thank you!
