### ISSUE TITLE
Default scan/connect period is too small

### ISSUE THREAD

**Issue by jackjansen** [hbldh/bleak#286]
* bleak version: develop
* Python version: 3.8
* Operating System: OSX
* BlueZ version (`bluetoothctl -v`) in case of Linux: 

### Description

Trying to connect to a set of devices with a long advertising interval (battery-conscious devices).

### What I Did

```
        async with bleak.BleakClient(device.address) as server:
            services = await server.get_services()
```

More often than not, this fails with a `bleak.exc.BleakError` exception. I think this is because the scan duration defaults to 5 seconds, while my devices use an 8 second interval to conserve battery. The BLE spec states that 10.24 seconds is the maximum allowable advertisement interval, so that would seem like a more reasonable default for the scanning duration, especially because scan results are not cached (but I'll create a separate issue for that).

**Comment by hbldh** [comment]
The changes in #279 and #285 will solve this better. The default on connect is 10 seconds there, and combined with the ability to connect directly by using `BLEDevice` in `BleakClient` will resolve this.
