### ISSUE TITLE
set default branch on GitHub to develop?

### ISSUE THREAD

**Issue by dlech** [hbldh/bleak#289]
I think it would be nice to set the default branch on GitHub to develop instead of master. This makes it easier for those forking and making pull requests to use the right branch for development. Also, it would be easier for users to find the latest CHANGELOG that included the unreleased changes, which is a nice way to know if that bug fix you need has been released yet or not.

**Comment by hbldh** [comment]
I agree. It would facilitate a better handling, even though it doesn't portray the true "production" state. Feel free to change it!

**Comment by dlech** [comment]
I don't think I have access to change repository settings.

**Comment by hbldh** [comment]
Understood. I had hoped that was part of the deal. I will change tomorrow.

**Comment by hbldh** [comment]
Done
