### ISSUE TITLE
Device gone forever after Ctrl-C or kill

### ISSUE THREAD

**Issue by 5frank** [hbldh/bleak#315]
* bleak version: 0.8.0
* Python version: 3.7.3
* Operating System: Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.50

### Description
If a bleak process with a active connection is terminated with Ctrl-C or kill SIGINT, the BLE device disappears forever. I am unable to reconnect and device do not show up in scan/discovery.
`sudo systemctl restart bluetooth` resolves the problem, so it is likely a issue with a "zombie connection" or something in bluez/dbus.

### What I Did

This reproduces the problem:

```python
import asyncio
from bleak import BleakClient
import sys
import os

async def main():
    address = sys.argv[1]
    pid = os.getpid()
    async with BleakClient(address) as client:
        while 1:
            print("press ctrl-C or enter `kill -2 {}` in another shell!".format(str(pid)))
            await asyncio.sleep(1)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
Traceback when pressing ctrl-C:
```
Traceback (most recent call last):
  File "connect_and_exit.py", line 72, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```

The following examples works as expected (i.e. BLE device show up in scan).
It might seem they should have the same behavior, but apparently not.

```python
async def test_Exception(address):
    async with BleakClient(address) as client:
        await asyncio.sleep(0.5)
        raise Exception

async def test_KeyboardInterrupt(address):
    async with BleakClient(address) as client:
        await asyncio.sleep(0.5)
        raise KeyboardInterrupt

async def test_SIGINT(address):
    pid = os.getpid()
    async with BleakClient(address) as client:
        await asyncio.sleep(0.5)
        os.kill(pid, signal.SIGINT)
```

Traceback when raising KeyboardInterrupt. Note that it differs from the one above!
```
Traceback (most recent call last):
  File "connect_and_exit.py", line 66, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "connect_and_exit.py", line 50, in main
    await test_KeyboardInterrupt(address)
  File "connect_and_exit.py", line 17, in test_KeyboardInterrupt
    raise KeyboardInterrupt
KeyboardInterrupt
```

I believe this problem was recently introduced as I have not seen it earlier (might have missed it).

Can anyone reproduce it on another system?
Ideas?

**Comment by 5frank** [comment]
unable to reproduce in MacOS btw

**Comment by hbldh** [comment]
If you terminate your application like this, the Bluetooth connection might still be active in the OS backend. Always make sure the `disconnect` method runs, or that the context manager is allowed to do its cleanup when exiting. Catch KeyboardInterrupts and left the program exit gracefully instead.

If you kill it from outside, you will most definitely be left with residual connections, especially in BlueZ and probably in Windows as well.

**Comment by 5frank** [comment]
Adding the following fixes it for SIGINT exit but I do not understand why. Should be the same as not implementing a signal handler at all?

```python
import signal
def signal_handler(sig, frame):
    raise KeyboardInterrupt
signal.signal(signal.SIGINT, signal_handler)
```

**Comment by 5frank** [comment]
Possible fix/workaround:
```python 
import asyncio
import os
import sys
import signal
import functools
from bleak import BleakClient
 
async def signal_handler(signo, loop):
    print('caught {0}'.format(signo.name))
    for task in asyncio.Task.all_tasks():
        if task is asyncio.tasks.Task.current_task():
            continue
        task.cancel()
 
async def main():
    address = sys.argv[1]
    pid = os.getpid()

    print("connecting to", address)
    async with BleakClient(address) as client:
        while 1:
            print("press ctrl-C or enter `kill -2 {}` in another shell!".format(str(pid)))
            await asyncio.sleep(1)

loop = asyncio.get_event_loop()

for signo in [signal.SIGINT, signal.SIGTERM]:
    func = functools.partial(asyncio.ensure_future, signal_handler(signo, loop))
    loop.add_signal_handler(signo, func)

loop.run_until_complete(main())
```
based on this: https://gist.github.com/nvgoldin/30cea3c04ee0796ebd0489aa62bcf00a

**Comment by dhalbert** [comment]
I added a cleanup routine using `atexit.register()` which runs through all my connections and disconnects them. This worked well and was cross-platform. I happened to be keeping a list of connections already.

**Comment by hbldh** [comment]
If you use the Ctrl-C soluton to break your program, you might break not inside the Bleak handling, but inside the asyncio loop instead and never run the client's cleanup. The `add_signal_handler` is a good way to handle it, as is a `atexit` solution. 

@5frank If you arrive at something that works fine, it would be very helpful to reduce it to a condensed form and make a PR adding it to the `examples` folder!

**Comment by 5frank** [comment]
I believe the expected behavior of a UNIX process it that it should exit gracefully on SIGINT. It seems a lot to require a exit handler to be implemented by the user in every script? Perhaps it is possible to add a default exit handler to bleak somehow without overriding other handlers?

**Comment by hbldh** [comment]
The expected behaviour you describe is that of your application, not of the components you use. Bleak is not an application, but a package with which to write your application. Had Bleak provided some kind of `run` functionality that kicks off a asyncio loop, then it could possibly be argued that it might take that responsibility, but now it only provides method with which you can interface with BLE devices. 

Bleak does provide cleanup functionality and `__aexit__` solutions for the user to call, but these - as you have discovered - can be circumvented by interupting the python process via external means. Bleak does not require every user to implement this, only those who desire to stop their applications in this fashion.

**Comment by 5frank** [comment]
`atexit` would be a lot cleaner but did not resolve my issue. I guess it runs to after "asyncio exit" and doesn't  trigger the cleanup code.

**Comment by dhalbert** [comment]
This is what we use: (https://github.com/adafruit/Adafruit_Blinka_bleio)

```python
        ...
        # Clean up connections, etc. when exiting (even by KeyboardInterrupt)
        atexit.register(self._cleanup)

    def _cleanup(self):
        """Clean up connections, so that the underlying OS software does not
        leave them open.
        """
        # Use a copy of the list because each connection will be deleted
        # on disconnect().
        for connection in self._connections.copy():
            connection.disconnect()
```
The `Connection` objects are our own, so this is what `disconnect()` does.
```python
    def disconnect(self) -> None:
        """Disconnects from the remote peripheral. Does nothing if already disconnected."""
        adap.adapter.delete_connection(self)
        adap.adapter.await_bleak(self._disconnect_async())
```
Crossing the sync-async boundary:
```python
    def await_bleak(self, coro, timeout=None):
        """Call an async routine in the bleak thread from sync code, and await its result."""
        # This is a concurrent.Future.
        future = asyncio.run_coroutine_threadsafe(coro, self._bleak_loop)
        return future.result(timeout)
```

**Comment by xloem** [comment]
Here was what I did.  `_connected` is kept as a list of connected devices.

```
async def _destroy(self):
    await asyncio.wait([device._client.disconnect() for device in _connected], return_when=asyncio.ALL_COMPLETED)
    _connected = []

@atexit.register
def _destroy():
    asyncio.get_event_loop().run_until_complete(_destroy())
```

**Comment by liqi0816** [comment]
> Had Bleak provided some kind of `run` functionality that kicks off a asyncio loop, then it could possibly be argued that it might take that responsibility.

...and indeed `asyncio.run` will run the cleanup. [It calls](https://github.com/python/cpython/blob/799f8489d418b7f9207d333eac38214931bd7dcc/Lib/asyncio/runners.py#L49) `loop.run_until_complete(loop.shutdown_asyncgens())` at exit.

```python
class Foo:
    async def __aenter__(self):
        print('__aenter__')

    async def __aexit__(self, *_):
        print('__aexit__')

async def main():
    async with Foo():
        await asyncio.sleep(1000)

asyncio.run(main())
```

You will see `'__aexit__'` printed even if Ctrl-C. Reliable and clean.

Maybe we should switch to `asyncio.run` in examples?

**Comment by dlech** [comment]
> Maybe we should switch to `asyncio.run` in examples?

We still support Python 3.6, so we would have to do something [like this](https://github.com/hbldh/bleak/pull/389/commits/c15c48d88744ebdfddac72b087638d5899f7d365).

**Comment by hbldh** [comment]
@dlech Impressive!

A bit off-putting in an example though? I might be better to send the use to the docs for that instead, e.g.

```python
if sys.version_info >= (3, 7):
    asyncio.run(show_disconnect_handling())
else:
     # N.B.: See <url> for a complete secure termination in Python 3.6.
     loop.run_until_complete(show_disconnect_handling())
```
Good to see that it is possible to handle though!

**Comment by dlech** [comment]
Yes, or turn it into a helper method.

**Comment by xloem** [comment]
an option is to merge the task cancellation approach with atext, by e.g. registering a cancellation function in the client object

**Comment by olsonap** [comment]
So how do I disconnect now that I've hit Ctrl C? I see how to program it in, but let's assume I only need to remove the connection once and will never improperly exit again, what do I do?

**Comment by dlech** [comment]
`bluetoothctl disconnect XX:XX:XX:XX:XX:XX`
