### ISSUE TITLE
corebluetooth returning "uuids" that are service names, like "Heart Rate" or "Device Information"

### ISSUE THREAD

**Issue by dhalbert** [hbldh/bleak#342]
* bleak version: 0.8.0 and tip of develop
* Python version: 3.8.2
* Operating System: macOS 10.15.7

I was startled to discover that corebluetooth appears to be returning English language strings for standard Bluetooth UUIDS, such as "Heart Rate".

In https://github.com/hbldh/bleak/blob/ccdac2388e882a5e5c446cf36df349fbfedce2e8/bleak/backends/corebluetooth/device.py#L45-L47
`cbuuids` can contain human-readable strings instead of strings that are UUIDs.

I was looking at the advertising data from a standard Heart Rate Monitor device (Scosche), and `cbuuids` contains this:
```python
(
    "Heart Rate",
    "Device Information",
    1725
)
```
bleak lowercases these, on the assumption they are uuids, but these are just readable strings.

So any attempt to determine if the advertised service is the Heart Rate Monitor service (0x180D) has to do a string comparison against "heart rate", instead of "0x180d".

I don't think bleak is doing this conversion, but it's coming directly from `kCBAdvDataServiceUUIDs`. I'm thinking `uuids.py` needs to contain a reverse dictionary to convert these strings back to hex for uniformity across platforms.

Am I missing something?? Has someone else encountered this? As usual Apple's documentation seems to be lacking details.

**Comment by hbldh** [comment]
This is highly undesired. I have not experienced this myself, but will try to reproduce it at the end of the week. Does this happen "inside" the client as well, after connection, or is it only in the advertisement service uuids?

**Comment by dhalbert** [comment]
It is what is returned in the advertisement data. I was trying to convert those strings to our own internal UUID objects (which parse the hex UUID strings), and got an error.

I think you would see this even on devices advertising Vendor IDs if they also provide Device Information Service, which most do.
