### ISSUE TITLE
Device connection opens notify, disconnection processing

### ISSUE THREAD

**Issue by lai-Ryan** [hbldh/bleak#354]
bleak ### version:0.8.0
Python version:3.7.2
Operating System:windows10
BlueZ version (bluetoothctl -v) in case of Linux: no
### Description
When the device is connected to notify, if the device is suddenly disconnected, how to determine and automatically reconnect?
### What I Did
When the connection is turned on, if the device is disconnected, you will get Error code: bleak.exc.BleakDotNetTaskError: System.Exception
Currently using exception handling, additional errors will still be displayed. What can be done in this part to realize that after opening the notification, if the device is disconnected, you can judge and reconnect!!
try:
expect bleak.exc.BleakDotNetTaskError: System.Exception:

**Comment by hbldh** [comment]
This is not an issue, but more of a question. Look at https://github.com/hbldh/bleak/issues/315 and the example here: https://github.com/hbldh/bleak/blob/develop/examples/disconnect_callback.py

A better reconnect exmaple will be present once #266 is completed.
