### ISSUE TITLE
Bleak Import Issue on Big Sur

### ISSUE THREAD

**Issue by yujie-tao** [hbldh/bleak#365]
* bleak version: 0.6.1
* Python version: 3.7.3
* Operating System: Mac Big Sur
* BlueZ version (`bluetoothctl -v`) in case of Linux:

Hi

When I try to execute the [example script ](https://github.com/hbldh/bleak/blob/develop/examples/discover.py), I get the "Bleak requires the CoreBluetooth Framework" exception.  After adding the line of `import CoreBluetooth`, I keep getting `bleak.exc.BleakError: Bluetooth device is turned off` error.I recently upgraded my system to Big Sur; I had no problem to run the test script before. Does any one know how to fix it?

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    loop.run_until_complete(run())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 8, in run
    devices = await discover()
  File "/Users/skytao/Downloads/osc-python-vr/env/lib/python3.7/site-packages/bleak/backends/corebluetooth/discovery.py", line 31, in discover
    raise BleakError("Bluetooth device is turned off")
bleak.exc.BleakError: Bluetooth device is turned off
[1]    30879 abort      python3 test.py
```

**Comment by hbldh** [comment]
First of all, try to upgrade Bleak to 0.9.1 and try again.

Other than that, it looks like you need to turn your Bluetooth adapter on: https://support.apple.com/en-hk/guide/mac-help/blth1008/mac

**Comment by yujie-tao** [comment]
Thanks for responding! When I switched to Bleak 0.9.1, it gave me error as `[1]    74763 abort      python3 test.py`. 

I do have the bluetooth on and also tried to switch it off and back on.

**Comment by hbldh** [comment]
I am not sure this is Bleak throwing an exception...

How have you installed your Python? Via Homebrew? You might need to do a reinstall of Python in that case. This issue might help: https://github.com/Homebrew/homebrew-core/issues/44996.

**Comment by yujie-tao** [comment]
Hi

I installed Python through the package installer on the python website. I tried to delete and reinstall the python but the error still remain.

I also tested on my friend's laptop (which is also running on Big Sur), the same error happened as well.

**Comment by hbldh** [comment]
Seems to be a problem with `pyobjc` on Big Sur: https://github.com/ronaldoussoren/pyobjc/issues/309#issuecomment-648350096

Try installing the required `pyobjc` libraries from the `pyobjc-7-branch` branch.

**Comment by yujie-tao** [comment]
I updated the PyObjC with the one under `pyobjc-7-branch`, sadly the issue still remains...

**Comment by hbldh** [comment]
I am not able to help any further I am afraid, since I have not macOS to test on at the moment and for quite some time into the future. Hopefully someone else can shed som more light on the matter.

**Comment by dhalbert** [comment]
I am running bleak successfully on Big Sur. My pip3 versions are:

bleak 0.9.1
pyobjc*  6.2

**Comment by dlech** [comment]
A crash in PyObjC v7 was fixed in PyObjC v7.0.1. See #372.

**Comment by alcpereira** [comment]
Have you tried #438 ?

**Comment by yujie-tao** [comment]
wow #438 helped to solve it! Thank you @alcpereira, will close this issue.
