### ISSUE TITLE
support for hexadecimal writing gatt now（or in develop）?

### ISSUE THREAD

**Issue by ZombiesYard** [hbldh/bleak#368]
* bleak version: 0.9.1
* Python version: 3.7.4
* Operating System: Windows10 2004
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

The methods provided in the document are successfully used and test under the Windows platform.I just want to know if there are plans to support write hexadecimal data at present or in the future, because I need this function on my own small project. If don't plan to support it, I can also rewrite the program on the hardware to achieve the effect I want.

**Comment by hbldh** [comment]
No, there are no plans for that. All backend APIs accept arrays of bytes and thus, so does Bleak. It is pretty easy to convert for yourself though before calling write method.
