### ISSUE TITLE
The scan result shows 'Unknown' name of the device

### ISSUE THREAD

**Issue by edward-jw-yu** [hbldh/bleak#371]
* bleak version: 0.9.1
* Python version: 3.7
* Operating System: win10 2004 19041

### Description
After I run the following code
```python
import asyncio
from bleak import BleakScanner

async def run():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```
It shows 'A4:C1:38:01:21:FC: Unknown'
But I find the device in the system shows name 'SigMesh'

**Comment by hbldh** [comment]
The Windows UWP Bluetooth API does not always provide a proper name for the device. I have explored a long time and the current state is the best that Bleak is capable of. Sorry.

**Comment by dlech** [comment]
Does this device actually send the name in the advertising data? For example by setting "complete local name" data?

**Comment by dlech** [comment]
Also see #175

**Comment by pjbosco** [comment]
I proposed a possible solution on #175.
