### ISSUE TITLE
Can we use "is_connected" before trying to "connect" first?

### ISSUE THREAD

**Issue by sneko** [hbldh/bleak#385]
* bleak version: 0.9.1
* Python version: 3.7
* Operating System: Mac

### Description

When using a BLEClient to do:
```
await ble_client.is_connected()
```
before connecting, it shows me this error:

```
  File "/Users/XXXXXXXXXXXXXXX/.venv/lib/python3.7/site-packages/bleak/backends/corebluetooth/client.py", line 123, in is_connected
    return manager.isConnected
AttributeError: 'NoneType' object has no attribute 'isConnected'
```

Whereas if I do:
```
await ble_client.connect()
await ble_client.is_connected()
```
I have no error.

Is there any specific return why is this happening? I saw it changed recently with https://github.com/hbldh/bleak/pull/323 @Carglglz @0ge

Thank you,

EDIT: it's like if I was in the else case https://github.com/hbldh/bleak/blob/develop/bleak/backends/corebluetooth/client.py#L49-L54

**Comment by dlech** [comment]
Thanks for the report. This is definitely a bug. I've made a PR to fix it.
