### ISSUE TITLE
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"

### ISSUE THREAD

**Issue by edward-jw-yu** [hbldh/bleak#423]
* bleak version: 0.9.1
* Python version: 3.7
* Operating System: win10
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description
I am using bleak in PyQt5 projects on win10
and after import bleak, the console printed 'QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"' when runing the PyQt5 project.
This caused my program failed to open the QFiledialog with Native windows. The program just hanged there like dead.

### What I Did

```
Missing MWE
```

**Comment by hbldh** [comment]
I cannot help you much here, given that I never tried using Qt with Bleak. But I expect that it does not play nice with `asyncio`. Try integrating with [`qasync`](https://pypi.org/project/qasync/) to make it work.

**Comment by edward-jw-yu** [comment]
Thank you

**Comment by JBrakefield** [comment]
I have this same issue happening now after reverting from Python 3.9 and Python 3.8. I get this same annoying warning if PyQt5 and bleak are both imported. My program ran fine on Python 3.9, but when trying to share my program and get the modules installed for someone else it was too difficult (pynnet installation issues and so forth). I can't remember how to get around them for python 3.9, and it is so much simpler to just use python 3.8 to get around that. However, this new warning/error is seemingly impossible to fix. I've tried everything including suppressing it with 'warnings' module (didn't work).

We either need a fix for this issue or a way to make things install more smoothly with python 3.9.

**Comment by dlech** [comment]
Related issue (for pywinrt backend): https://github.com/microsoft/xlang/issues/690

I think the solution is probably to make sure Qt calls and Bleak calls each stay on their own thread.

**Comment by dlech** [comment]
Also see https://github.com/hbldh/bleak/issues/580#issuecomment-867928327 for another possible workaround.

**Comment by JBrakefield** [comment]
> Also see [#580 (comment)](https://github.com/hbldh/bleak/issues/580#issuecomment-867928327) for another possible workaround.

I tried adding `from winrt import _winrt

_winrt.unint_apartment()`

but python says "AttributeError: module 'winrt._winrt' has no attribute 'unint_apartment'"

**Comment by dlech** [comment]
Looks like I spelled "uninit" wrong.

**Comment by JBrakefield** [comment]
ahh thanks! I think this fixed it!

**Comment by bstarbuck3** [comment]
from bleak_winrt import _winrt
_winrt.uninit_apartment()

**Comment by dlech** [comment]
FYI, this workaround is no longer needed since Bleak v0.14.x.
