### ISSUE TITLE
What happens to the response?

### ISSUE THREAD

**Issue by littleblackfish** [hbldh/bleak#425]
I am new to BLE so excuse me if I'm missing a point here.

I understand there is a parameter so I can do `write_gatt_char(uuid, value, response=True)` to do a "write-with-response", but how do I actually get the response? 

No return, and I tried reading the same character back, but the expected response (per specs of this device) is not there.

**Comment by dlech** [comment]
The response is handled by the OS. The async function will not return until the response is received. The response doesn't contain any useful data. So it is probably better to think of it as "wait for acknowledgement of receipt before continuing".

**Comment by littleblackfish** [comment]
Thank, you. I am trying to map the attached scheme from the specs of my device of interest to this library. I am writing [01 00] to the mentioned PMD control point, but since `write_gatt_char()` does not return anything, where would you suggest I look for the response? 

![image](https://user-images.githubusercontent.com/7980688/104859239-ce833500-58f1-11eb-8780-688e00ee2b1d.png)

**Comment by Carglglz** [comment]
@littleblackfish I think you need to read the response from PMD control point `read_gatt_char(PMD_CHAR_UUID)` after writing to it.

**Comment by littleblackfish** [comment]
Thank you for the input, this is what I thought, although it appears not to be the case. The same documentation specifies what happens when your read the PMD_CHAR, and that respond does not appear to change after writing to this UUID.

![image](https://user-images.githubusercontent.com/7980688/104964022-a951fd80-59a9-11eb-8d67-a25600690c8d.png)

**Comment by dlech** [comment]
did you enable notifications?

**Comment by littleblackfish** [comment]
Ah, thank you, that sounds like a very viable solution. I will report back as soon as I can try (device is not with me at the moment). 

I realize this is primarily my lack of experience with BLE rather than a library issue but guidance is much appreciated.

**Comment by littleblackfish** [comment]
Yes! This was the way. Thank you.
