### ISSUE TITLE
get_discovered_devices() is not actually async

### ISSUE THREAD

**Issue by dlech** [hbldh/bleak#489]
Technically speaking, `BleakScanner.get_disovered_devices()` does not need to be async since none of the implementations await anything.

However, changing it would be a major breaking change. We could probably lessen the impact by doing something similar to https://github.com/hbldh/bleak/commit/bc6da1e81a677ad9065936f52781bc15693732a8 to make it not quite so breaking if we decide it is worth making the change (for some time, it would return an object that is both a list and a future that gives a warning about the change).

**Comment by hbldh** [comment]
Yes, I agree. It absolutely does not need to be async. It should be changed. Apply the same warning procedure and let's try to get it properly changed in a future release.
