### ISSUE TITLE
Minor WinRT backend bugs

### ISSUE THREAD

**Issue by devanlai** [hbldh/bleak#536]
* bleak version: develop (at 0f74fc0)
* Python version: 3.9.5
* Operating System: Windows 10

### Description

I noticed a couple of minor bugs while trying out the winrt backend that weren't really big enough to warrant making two pull requests.

First, `BleakScannerWinRT` still implements the deprecated `get_discovered_devices()` method instead of the new `discovered_devices` property, so calls like `find_device_by_address` fail with:

    TypeError: Can't instantiate abstract class BleakScannerWinRT with abstract method discovered_device

Second, in `_received_handler()`, the UUID constructor throws an assertion when attempting to process 128-bit UUIDs because the `bytes` parameter is supposed to have type, well, `bytes`, but instead it gets a `bytearray`.

```
        # 0x21 is service data with 128-bit UUID
        for section in event_args.advertisement.get_sections_by_type(0x21):
            data = bytearray(CryptographicBuffer.copy_to_byte_array(section.data))
            service_data[str(UUID(bytes=data[15::-1]))] = data[16:]
```

Passing in `bytes(data[15::-1])` to convert to `bytes` first is sufficient to fix the assert.

**Comment by dlech** [comment]
> I noticed a couple of minor bugs while trying out the winrt backend that weren't really big enough to warrant making two pull requests.

It sounds like these are worth fixing so one or two pull requests seem warranted to me. :wink:
