### ISSUE TITLE
Generic Access Profile service not visible on Ubuntu 21.04

### ISSUE THREAD

**Issue by Crimson-Crow** [hbldh/bleak#553]
* bleak version: 0.11.0 and 0.12.0b1
* Python version: 3.9.5
* Operating System: Windows and Ubuntu 21.04
* BlueZ version : 5.56

### Description
On my Bluetooth device, I'm trying to access information (ex: device name) from the Generic Access Profile service (service UUID: 00001800-0000-1000-8000-00805f9b34fb).
Using the `service_explorer.py` example, the service and its characteristics show up on Windows, but not Ubuntu. Trying to access info directly through handle or UUID also fails on Ubuntu.
All other services/characteristics are displayed and work as intended.

**Comment by dlech** [comment]
BlueZ hides characteristics that is uses for other things for some reason. The device name characteristic is on of those. We have a workaround that allows you to read the characteristic directly by UUID.

https://github.com/hbldh/bleak/blob/07585524b069f1f6a456b53dd8922c85462faaec/bleak/backends/bluezdbus/client.py#L706-L716

But the workaround doesn't add it to the list of services or characteristics.
