### ISSUE TITLE
CoreBluetooth: Callback gets `_NSInlineData`, not `bytearray`, causing methods to fail

### ISSUE THREAD

**Issue by jeffsf** [hbldh/bleak#560]
```
(venv) [jeff@mini ~/devel/pyDE1]$ python --version
Python 3.9.5
(venv) [jeff@mini ~/devel/pyDE1]$ pip list
Package                        Version
------------------------------ -------
aiologger                      0.6.1
bleak                          0.11.0
pip                            21.0.1
pyobjc-core                    7.1
pyobjc-framework-Cocoa         7.1
pyobjc-framework-CoreBluetooth 7.1
pyobjc-framework-libdispatch   7.1
setuptools                     56.0.0
```
macOS 10.14.6

### Description

On a notification callback, I wanted to be able to log the hex value received. Expecting a `bytearray` from the typing in the `bleak` module, I used `data.hex()`. As the `data` was not a `bytearray`,  it failed.

```
Traceback (most recent call last):
  File "/Volumes/miniup-users/jeff/devel/pyDE1/scale_direct.py", line 112, in button_handler
    logger.info(data.hex())
AttributeError: '_NSInlineData' object has no attribute 'hex'
```

As can be seen in the code below, coercing it to a `bytearray` is very straightforward. As the `_NSInlineData` generally can be accessed as if it is a `bytearray`, it may not be the case that coercing _every_ occurrence is worthwhile from a performance perspective. I have not timed or otherwise evaluated the "cost" of that operation.

### What I Did

```
async def button_handler(sender: int, data: bytearray):
    logger = logging.getLogger('Button')
    # if not isinstance(data, (bytearray, bytes)):
    #     logger.error(f"Button handler expected bytearray, not {type(data)}")
    #     data = bytearray(data)
    logger.info(data.hex())
```

![image](https://user-images.githubusercontent.com/1946364/120692063-1eefcf00-c45c-11eb-97b1-2c2e426a373b.png)

Full context at the end of the description of #559

**Comment by dlech** [comment]
I think we should cast to `bytearray` like we already do for the `read_*` methods.
