### ISSUE TITLE
BleakDotNetTaskError Could not get GATT characteristics AccessDenied 

### ISSUE THREAD

**Issue by ertex** [hbldh/bleak#599]
* bleak version: 0.12.1
* Python version: 3.9
* Operating System: Win 10  [Version 10.0.19042.1083]
* BlueZ version (`bluetoothctl -v`) in case of Linux:
* Bluetooth Firmware Version: HCI 8.256 / LMP 8.256

### Description

Similar to Issue #257 #222 From what I understand

I am trying to connect to a BLE Device using example code and get exceptions.
For reference I have previously interfaced with the device using closed source software without issues with the same hardware. 

Noteworthy is that the device contains three characteristics with the same UUIDs related to the HID Service since the HID service seems to be the thing causing trouble.

### What I Did

Running the example code for Services I get the following output:
```
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\Measure\venv\BLE-test3.py", line 32, in <module>
    loop.run_until_complete(print_services(ADDRESS))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\HP\PycharmProjects\Measure\venv\BLE-test3.py", line 24, in print_services
    async with BleakClient(mac_addr) as client:
  File "C:\Users\HP\PycharmProjects\Measure\venv\lib\site-packages\bleak\backends\client.py", line 61, in __aenter__
    await self.connect()
  File "C:\Users\HP\PycharmProjects\Measure\venv\lib\site-packages\bleak\backends\winrt\client.py", line 227, in connect
    await self.get_services(use_cached=use_cached)
  File "C:\Users\HP\PycharmProjects\Measure\venv\lib\site-packages\bleak\backends\winrt\client.py", line 449, in get_services
    raise BleakDotNetTaskError(
bleak.exc.BleakDotNetTaskError: Could not get GATT characteristics for <_winrt_Windows_Devices_Bluetooth_GenericAttributeProfile.GattDeviceService object at 0x000001A15CF7F290>: AccessDenied
```
By commenting out the ``` raise BleakDotNetTaskError( ``` in the file [winrt\client.py](https://github.com/hbldh/bleak/blob/7e0fdae6c0f6a78713e5984c2840666e0c38c3f3/bleak/backends/winrt/client.py#L449-L454) that the traceback is refering to, Bleak seems to work fairly normal, with the exception that the HID service has no characteristics.

**Comment by dlech** [comment]
Yes, not being able to access the HID service is a known issue with Windows. I think we need to add a parameter to only enumerate selected services and characteristics (and descriptors?) when connecting to a device.

Windows and Mac actually have OS APIs to do this (and theoretically this is better for battery life according to Apple). On Linux, all services and characteristics will still be enumerated by we can fake it in Bleak and filter what BlueZ sends us.
