### ISSUE TITLE
memory leak in bluetooth scanning 

### ISSUE THREAD

**Issue by KrisQdt** [hbldh/bleak#634]
* bleak version: 0.12.1
* Python version: 3.9.6
* Operating System: Windows 10
* BlueZ version (`bluetoothctl -v`) in case of Linux: 

### Description

I just want to make a scanner bluetooth which parse the advertise and display some alert.
This is a very simple example which display on mac address seen which works but the memory increase very quickly

```python
import asyncio
from bleak import BleakScanner

def detection_callback(device, advertisement_data):
	mac = device.address
	print(mac)

async def run():
	
	scanner = BleakScanner(scanning_mode = "active")
	scanner.register_detection_callback(detection_callback)

	await scanner.start()
	await asyncio.sleep(100000)
	await scanner.stop()


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

Is there way to correct that?

Thank for your help

**Comment by dlech** [comment]
Yes, there is a very bad memory leak in the `winrt` library. Can you try #609?
