### ISSUE TITLE
[solved] start_notify() gives write not permitted bluez error

### ISSUE THREAD

**Issue by kazola** [hbldh/bleak#669]
* bleak version: 0.12
* Python version: 3.9
* Operating System: linux
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.5x

### Description

start_notify() method was giving back a "write not permitted" bluez error.

### What I Did

Updating bluez from 5.5x to 5.61 solved the issue.

**Comment by dlech** [comment]
Thanks for sharing. It doesn't sound like there is anything to do in Bleak, so we can close this issue.

**Comment by kazola** [comment]
5.62 gives the error, too. Re-checked again that 5.61 works.
