### ISSUE TITLE
Bleak not working Issue on MacOS 12.0.1 Monterey

### ISSUE THREAD

**Issue by Ironman-007** [hbldh/bleak#683]
* bleak version: 0.11.0
* Python version: 3.9.7
* Operating System: MacOS 12.0.1 Monterey
* BlueZ version (`bluetoothctl -v`) in case of Linux: n/a

### Description

Python3 program with Bleak can not discover any devices.

I'm trying to develop a GUI using Python (with Bleak lib) on my mac to talk to an nRF52840 board through BLE.
But the program can not find any BLE devices.

### What I Did
I firstly test this demo from [Bleak repo](https://github.com/hbldh/bleak):

```
import asyncio
import CoreBluetooth

from bleak import discover

async def main():
    print("main()")
    devices = await discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

There is no output.
I reinstalled the python3 (by using brew), but there is still no output.

When I tried this demo on my PC, it's working, and can find all Bluetooth devices around.

Anyone can help me with this? Thanks in advance! :)

**Comment by dlech** [comment]
Sorry, we haven't figured out a solution to it yet. Please subscribe to issue #635 for updates. Closing this one as a duplicate.
