### ISSUE TITLE
Problem connecting to BLE devices with Windows

### ISSUE THREAD

**Issue by corentinbettiol** [hbldh/bleak#70]
* bleak version: 0.4.2
* Python version: 3.7.3
* Operating System: Windows 10

### Description

On linux (`backends/bluezdbus/client.py`), `connect()` function uses `discover()` with a timeout : `await discover(timeout=0.1, loop=self.loop)` ([here](https://github.com/hbldh/bleak/blob/master/bleak/backends/bluezdbus/client.py#L64)).

On windows (`backends/dotnet/client.py`), `connect()` function uses `discover()` with a defined value: `devices = await discover(2.0, loop=self.loop)` ([here](https://github.com/hbldh/bleak/blob/master/bleak/backends/dotnet/client.py#L89)), which leads to random errors due to the fact that Windows is unable to discover the device to connect to within 2 seconds.

Since `discover()` [has a timeout var](https://github.com/hbldh/bleak/blob/master/bleak/backends/dotnet/discovery.py#L28), it can be good to use `timeout=2.0` instead of `2.0` in `client.py`, so developers can adapt the value without having to manually change Bleak.

**Comment by hbldh** [comment]
Thank you for your ideas. I agree, I have thought about this as well. My initial idea had been to not have any keyword argument at all for the `connect` method, but I think I might have to reconsider this. 
I will probably make a temporary fix in version 0.4.3 to give users the configurability you ask for, but I have an idea for a more permanent solution which requires a lot more time to develop; time I do not have right now I am afraid. I will get back to you here when I have made some modifications and/or plans.

**Comment by corentinbettiol** [comment]
Thank you for your quick answer, I will look at v0.4.3 when it will be available:)

**Comment by hbldh** [comment]
Released 0.4.3 yesterday. Timeout keyword is now available in both BlueZ and .NET backend.

**Comment by sonus89** [comment]
I have a similar problem. 
Windows 10 + Python 3.7 + bleak
I can not even import BleakClient from bleak
I also tried bleson with no result...
I can only discover / scan / list nearby devices but unable to connect.

Any idea?

**Comment by hbldh** [comment]
@sonus89 please create a new issue and add code and traceback of errors there.
