### ISSUE TITLE
Closing ble connection with a device of specific name

### ISSUE THREAD

**Issue by 94929** [hbldh/bleak#703]
### Description
Hi, is there a way to list up all BLE-connected devices?
Let say my Bluetooth speaker is manually connected to my mac and I want to disconnect it using Bleak.
Would this be possible?

My intention here is that I have a ble device and have successfully connected with bleak.
However, whenever my python script dies (which is used to make the ble connection), the ble connection between the ble device and my mac is not disconnected automatically.
Thus, I'm trying to manually disconnect my ble device in advance, whenever I'm running the python script to make a new connection.

### What I Did
I tried to list up all BLE devices but only the ones that are not connected to any device show up.
If connected devices are shown up in the ble discovery, I believe I can disconnect them easily.

Thanks in advance.

**Comment by dlech** [comment]
> Hi, is there a way to list up all BLE-connected devices?

Not currently. Please see #367.
