### ISSUE TITLE
Use of logging.error (instead of logger.error) affects other configured logger's 

### ISSUE THREAD

**Issue by tcamise-gpsw** [hbldh/bleak#725]
* bleak version:  0.14.0a1 
* Python version: 3.8.8
* Operating System: MacOS 12

### Description

Sorry for any logging misnomers here as I'm not a pro with it...

The recent addition to BleakScannerCoreBluetooth() to log errors in Mac OS 12 when service UUID's are not set is using the global logger instead of getting the file logger.

That is, it is doing:

```
logging.error(
    "macOS 12 requires...
```

instead of:

```
logger.error(
    "macOS 12 requires...
```

This is causing strange behavior in my project when enabling bleak logging. I believe this is unintended on bleak's part since everywhere else in the bleak code uses "logger".

**Comment by dlech** [comment]
Oops. Happy to take a pull request to fix this.
