### ISSUE TITLE
Quick question about memoryview() in client.write_gatt_char (WinRT)

### ISSUE THREAD

**Issue by lakshjaisinghani** [hbldh/bleak#746]
Hey bleak team, 

**OS:** Windows 10
**bleak:** 0.14.1
**python:** 3.7.9

I am trying to learn about how your library works by building a basic version from scratch on windows. In the code snippet linked below, I don't understand how a `winrt.windows.storage.streams.Buffer` can be used in `memoryview()` as it only takes byte arrays as arguments. 

https://github.com/hbldh/bleak/blob/77a9300a3be94911d4e2c603d7a023791d96d53a/bleak/backends/winrt/client.py#L607-L615

If you implement a simple data writer from scratch:
```python
from bleak_winrt.windows.storage.streams import Buffer # I'm using  from winrt.windows.storage.streams import Buffer
data =  b'\xEA\x38\x00\x01\x01'

buf = Buffer(len(data))
buf.length = buf.capacity
with memoryview(buf) as mv:
    mv[:] = data
```

You get a `TypeError`:
 ```
TypeError: memoryview: a bytes-like object is required, not '_winrt_Windows_Storage_Streams.Buffer'
```

How do you guys make it work in the bleak backend?

### Current Workaround
I used this instead to write the data:
```Python
data =  b'\xEA\x38\x00\x01\x01'

writer = DataWriter()
writer.write_bytes(list(data))
buf = writer.detach_buffer()

# buf ready to be used, for example
result = await descriptor.obj.write_value_with_result_async(buf)
```

**Comment by dlech** [comment]
We forked the `pywinrt` code generation tool from Microsoft and made many bug fixes and improvements. See https://github.com/dlech/xlang. That fork contains CI build artifacts that contain a full build of the WinRT projection if you need more than what the `bleak-winrt` package provides.

**Comment by dlech** [comment]
In particular, https://github.com/dlech/xlang/commit/9f00705a639adfdc340e728f73f364832fa58f14 makes `IBuffer` a bytes-like object. This can be used with more than just `memoryview`. For example, using `struct.pack_into()` can make the code much more readable if the data contains discrete values.

```python
buf = Buffer(5)
buf.length = 5
struct.pack_into("<BHBB", buf, 0, 0xEA, 0x0038, 0x01, 0x01)

result = await descriptor.obj.write_value_with_result_async(buf)
```

**Comment by lakshjaisinghani** [comment]
That's prretty cool!

Thanks for helping out @dlech.
