### ISSUE TITLE
there are no api to read characteristic name

### ISSUE THREAD

**Issue by jinxiangwzh** [hbldh/bleak#747]
* bleak version:
* Python version:
* Operating System:
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

there are no api to read characteristic name.

![lADPJwY7RVoMEDbNBQDNAkA_576_1280](https://user-images.githubusercontent.com/17423179/151136151-b35f8fa1-3528-442a-9859-1ccb586b399d.jpg)

### What I Did

It is preferable if an issue contains a [Miminal Workable Example](https://stackoverflow.com/help/minimal-reproducible-example).
This will otherwise be one of the first questions you will get as a response.

It is also preferable if that example is not dependent on a specific peripheral device, but can be run and
reproduced with other BLE peripherals as well.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here as well.
```

**Comment by hbldh** [comment]
There is the `characteristic.description` that provides this information, if available.

**Comment by dlech** [comment]
https://bleak.readthedocs.io/en/latest/api/index.html#bleak.backends.service.BleakGATTService.description
