### ISSUE TITLE
Would you be interested in a FTMS_client as an example?

### ISSUE THREAD

**Issue by WouterJD** [hbldh/bleak#777]
**Describe the solution you'd like**
discover and server_explorer.py are a good start to create a client and I managed to create an FitnessMachineServer client.

**Describe alternatives you've considered**
If you like, I can create a sample code (removing all application dedicated stuff) for reference.

**Additional context**
This example can be added to the examples

**Comment by dlech** [comment]
Feel free to share code ideas https://github.com/hbldh/bleak/discussions/categories/ideas.
