### ISSUE TITLE
Slow connection with nest_asyncio

### ISSUE THREAD

**Issue by diogotecelao** [hbldh/bleak#793]
* bleak version: 0.14.2
* Python version: 3.8.6
* Operating System: Windows 10 Home
* Computer specs: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 12.0 GB RAM

### Description

Trying to establish a connection with a `nest_asyncio` applied considerably slows down the connection ~7 times (takes 21 seconds). If I comment out the `nest_asyncio.apply()`, the connection is no longer slow.

I've tested this behaviour in several computers. However, in one of them it didn't happen (it was fast with our without `nest_asyncio`), possibly because it's an extremely fast computer.

### What I Did

```
import asyncio
import nest_asyncio
from bleak import BleakClient
import time


def connect_to_device(mac_address) -> None:
    loop = asyncio.new_event_loop()
    set_connection(mac_address, loop)


def set_connection(mac_address, loop):
    loop.run_until_complete(establish_connection(mac_address, loop))


async def establish_connection(mac_address: str, loop):
    print('> Establishing a new BTH connection with {device}'.format(device=mac_address))
    client = BleakClient(mac_address, loop=loop)
    init_time = time.time()
    await client.connect()
    print('> Connection established. Elapsed time: {elapsed_time}'.format(elapsed_time=time.time()-init_time))
    await client.disconnect()

if __name__ == '__main__':
    nest_asyncio.apply()
    connect_to_device('F3:87:21:F0:A7:7C')
```

**Outputs:**

With `nest_asyncio.apply()`:
```
> Establishing a new BTH connection with F3:87:21:F0:A7:7C
> Connection established. Elapsed time: 21.593122720718384
```

Without `nest_asyncio.apply()`:
```
> Establishing a new BTH connection with F3:87:21:F0:A7:7C
> Connection established. Elapsed time: 3.2514888286590576
```

**Comment by hbldh** [comment]
This is not an issue with bleak, is it?. You should raise this issue with the `nest_asyncio` repo instead.

**Comment by diogotecelao** [comment]
@hbldh I believe this is a problem with bleak and not with `nest_asyncio`. I have been using `nest_asyncio` with several different features (some of them requiring high-speed data transfer) without problems.
In addition, bleak is only affected by the `nest_asyncio` in the connect step. It is not affected for example during message exchange.

**Comment by hbldh** [comment]
This is not a prioritized issue, since it only surfaces when using another third party package. If you could find out why and fix the issue in bleak that you suspect is there we will definitely accept a or for this.
