### ISSUE TITLE
read_gatt_char picks garbage values from cache

### ISSUE THREAD

**Issue by ps2229** [hbldh/bleak#803]
* bleak version:0.14.2
* Python version:3.9
* Operating System:Windows
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description
When using read_gatt_char bleak picks garbage values from the cache with an exception of sometimes the correct values and if use_cached is turned off then it picks only 0x01 in values.

**Comment by dlech** [comment]
Can you give a minimal reproducible example program? Have you tried the suggestions in the troubleshooting guide in the docs? In particular, logging bluetooth packets is particularly useful to see if the device is actually sending 0x01 or not.
