### ISSUE TITLE
Passive Scanning with BlueZ

### ISSUE THREAD

**Issue by ch701x** [hbldh/bleak#814]
* bleak version: 0.14.1
* Python version: 3.9
* Operating System: Linux
* BlueZ version (`bluetoothctl -v`) in case of Linux: v5.64

### Description

I'd like to implement passive scanning through Bleak. I have a very noisy Bluetooth environment, so active scanning tends to cause some problems.

`hcitool` makes it possible to run a passive scan with BlueZ directly but it doesn't appear Bleak yet supports the functionality. Is there a plan in implement this feature into Bleak?

**Comment by dlech** [comment]
Please see #606 (duplicate feature request).

**Comment by livestock701x** [comment]
I saw that ticket, but it wasn't clear by the conversation that this feature had actually be slated to be completed nor is it on the roadmap. Is there an estimated time to completion?

**Comment by dlech** [comment]
AFAIK, the API is still behind the `--experimental` in BlueZ, so I haven't been in a hurry to implement it. Always happy to take a pull request though.
