### ISSUE TITLE
Distinguish Advertisement Data and Scan Response Data

### ISSUE THREAD

**Issue by RAlexeev** [hbldh/bleak#815]
* bleak version: 0.14.2

### Description

Could you clarify about a limitation of the library, is it possible to distinguish data, received by the first advertisement packet (PDU type: `ADV_IND`) and the subsequent scan response packet (PDU type: `SCAN_RSP`) from a specific device? Right now, launching the example https://github.com/hbldh/bleak/blob/develop/examples/discover.py, I see that it returns both advertisement data and scan response data joined together. I would like to see exactly which data were received through advertisement packet and which one through scan response packet. Is it possible to realize using Bleck library?

**Comment by dlech** [comment]
It is only technically possible on Windows, not on other OSes. We made Windows behave like the other OSes in Bleak for consistency and because it caused issues for many users.

**Comment by RAlexeev** [comment]
Many thanks for your clarification.
