### ISSUE TITLE
AttributeError in `__enter__` when instantiating BleakClient

### ISSUE THREAD

**Issue by labishrestha** [hbldh/bleak#834]
* bleak version: 0.14.12
* Python version: 3.9.12
* Operating System: Windows
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

- AttributeError in `__enter__` when instantiating BleakClient
- Tends to happen intermittently, possibly when a previous instance wasn't GC'd yet or something.
- Will stop occurring after about 5 seconds

### What I Did

![image](https://user-images.githubusercontent.com/10927212/170147378-72a66dc9-d47e-43c6-a642-6fa9cba0af87.png)

**Comment by elupus** [comment]
You cant call "with" you must use "async with"
