### ISSUE TITLE
Raspberry Pi Zero W only connecting to second of two devices

### ISSUE THREAD

**Issue by elisalle** [hbldh/bleak#848]
* bleak version: 0.14.3
* Python version: 3.9.2
* Operating System: Debian GNU/Linux 11 (bullseye) (armv6l)
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.55

### Description

I attempted to run the [two devices example](https://github.com/hbldh/bleak/blob/develop/examples/two_devices.py) from the Bleak repo. I expected Bleak to connect to both devices and show the notifications of each. Instead, Bleak complained that it expected a coroutine.
After fixing that, I ran into a different issue; Bleak would only connect to the second of the two devices of which the MAC address was listed.

### What I Did

I attempted to run the two devices example mentioned above on a Raspberry Pi Zero W, connecting to two ESP32 devices. Unfortunately, this threw the following error:
```
Traceback (most recent call last):
  File "/home/merlin/freezer-watchdog-hub/temp.py", line 35, in <module>
    asyncio.run(
  File "/usr/lib/python3.9/asyncio/runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got <_GatheringFuture pending>
```
I then saw that the asyncio.gather call on [line 31 of the example](https://github.com/hbldh/bleak/blob/develop/examples/two_devices.py#L31) wasn't being awaited, so I changed the `main()` function to the following:
```py
async def main(addresses):
    return await asyncio.gather(*(connect_to_device(address) for address in addresses))
```
When I ran that, I no longer got an error. Unfortunately, however, Bleak then only connected to and showed notifications from the second MAC address listed. After it disconnected from the device with that MAC address, the program would not do anything else, but just hung without exiting. Whenever I changed the order of the MAC addresses in the list being passed to main, the second MAC address in the list would be the one to whose associated device Bleak would connect.
My code is as follows:
```py
import asyncio

from bleak import BleakClient

notify_uuid = 'b833f6f1-c616-4a05-a9f6-0dcbdc0d750f'


def callback(sender, data):
    print(sender, data)


async def connect_to_device(address):
    print("starting", address, "loop")
    async with BleakClient(address, timeout=5.0) as client:

        print("connect to", address)
        try:
            await client.start_notify(notify_uuid, callback)
            await asyncio.sleep(10.0)
            await client.stop_notify(notify_uuid)
        except Exception as e:
            print(e)

    print("disconnect from", address)


async def main(addresses):
    return await asyncio.gather(*(connect_to_device(address) for address in addresses))


if __name__ == "__main__":
    asyncio.run(
        main(
            [
                # in this order, Bleak will connect to the address starting with 58
                # when the order is switched, it will connect to the device staring with 4C
                "4C:EB:D6:75:B5:52",
                "58:BF:25:80:7E:56",
            ]
        )
    )
```

My file was called temp.py. Therefore, I ran the following command:
`python3 temp.py`
When the MAC address starting with 58 was second in the list, the output was as follows:
```
(venv) merlin@rpi1-20220320:~/freezer-watchdog-hub$ python3 temp.py 
starting 4C:EB:D6:75:B5:52 loop
starting 58:BF:25:80:7E:56 loop
connect to 58:BF:25:80:7E:56
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
disconnect from 58:BF:25:80:7E:56
```
after which the program would stop doing anything, and I would press Ctrl+C.
When the MAC address starting with 4C was second in the list, this was the output:
```
(venv) merlin@rpi1-20220320:~/freezer-watchdog-hub$ python3 temp.py 
starting 58:BF:25:80:7E:56 loop
starting 4C:EB:D6:75:B5:52 loop
connect to 4C:EB:D6:75:B5:52
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
41 bytearray(b'\x00\x01\x01\x00')
41 bytearray(b'\x01\x01\x01\x00')
disconnect from 4C:EB:D6:75:B5:52
```
after which the program would again stop doing anything, and I would press Ctrl+C.

This may be related to #618 , but unfortunately, I wasn't able to try the solution there, since the OP there doesn't mention how they connected to the `BLEDevice` instance other than extracting a MAC address from it and connecting to that using a `BleakClient`.

**Comment by koenvervloesem** [comment]
Maybe try scanning for devices first and then after the scan is complete connect to the found devices, like in https://github.com/hbldh/bleak/issues/630#issuecomment-991877805. This helped me solve a similar issue.

**Comment by elisalle** [comment]
That's a good idea; I'll try that and report back if it works.

**Comment by elisalle** [comment]
You're right, it worked. Thanks a lot!
Perhaps it would be a good idea to add a note about this behaviour to the [troubleshooting](https://bleak.readthedocs.io/en/latest/troubleshooting.html) section of the documentation. What are peoples' thoughts on this?

**Comment by dlech** [comment]
Don't feel too bad, I think we all do that now and then. :wink:
