### ISSUE TITLE
Using detection_callback with service UUID in MacOS 12.4

### ISSUE THREAD

**Issue by damianjwilliams** [hbldh/bleak#961]
* bleak version: 0.15.1
* Python version: 3.8
* Operating System: MacOS 12.4 and Windows 10

### Description

_Describe what you were trying to get done._
Use detection_callback.py example with MacOS 12.4

_Tell us what happened, what went wrong, and what you expected to happen._
I wish to read advertising data from an  ESP32 peripheral using the `detection_callback.py` example, but no advertising data is displayed.  I know that when using MacOS 12.4, service UUIDs need to be provided to read advertising data (as discussed [extensively](https://github.com/hbldh/bleak/pull/692), but I am still struggling to get it to work.  

### What I Did

My ESP32 is set up as a server using the [BLE_server example](https://gist.github.com/damianjwilliams/07ef4250c572d35952d66b1ae8fc4625) from Arduino. The ESP32 will intermittently broadcast advertising data including a service UUID (in this case, `4fafc201-1fb5-459e-8fcc-c5c9c331914b`) 

 It all works as expected on my PC running Windows 10: 
I use `discover.py` example to determine the ESP32 MAC address.
Output: 
`94:B9:7E:DA:7C:FE: Long name works now`

then `service_explorer.py` to confirm the service UUID. 
Ouput:
```INFO:__main__:[Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Attribute Profile
INFO:__main__:	[Characteristic] 00002a05-0000-1000-8000-00805f9b34fb (Handle: 2): Service Changed (indicate), Value: None
INFO:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 4): Client Characteristic Configuration) | Value: b'\x02\x00'
INFO:__main__:[Service] 00001800-0000-1000-8000-00805f9b34fb (Handle: 20): Generic Access Profile
INFO:__main__:	[Characteristic] 00002a00-0000-1000-8000-00805f9b34fb (Handle: 21): Device Name (read), Value: b'Long name works now'
INFO:__main__:	[Characteristic] 00002a01-0000-1000-8000-00805f9b34fb (Handle: 23): Appearance (read), Value: b'\x00\x00'
INFO:__main__:	[Characteristic] 00002aa6-0000-1000-8000-00805f9b34fb (Handle: 25): Central Address Resolution (read), Value: b'\x00'
INFO:__main__:[Service] 4fafc201-1fb5-459e-8fcc-c5c9c331914b (Handle: 40): Unknown
INFO:__main__:	[Characteristic] beb5483e-36e1-4688-b7f5-ea07361b26a8 (Handle: 41): Unknown (read,write), Value: b'Hello World says Neil'
```
The correct service UUID is given in the second to last line. 
I can also see this service UUID using the BLE scanner app I have on my phone. 

I can then run `detection_callback.py` with this service_uuid
(i.e. including `scanner = BleakScanner(simple_callback, ["4fafc201-1fb5-459e-8fcc-c5c9c331914b"])`).
Output:
```(re)starting scanner
2022-08-24 22:10:29,835 __main__ INFO: 94:B9:7E:DA:7C:FE RSSI: -62, AdvertisementData(service_uuids=['4fafc201-1fb5-459e-8fcc-c5c9c331914b'])
2022-08-24 22:10:29,842 __main__ INFO: 94:B9:7E:DA:7C:FE RSSI: -62, AdvertisementData(local_name='Long name works now', service_uuids=['4fafc201-1fb5-459e-8fcc-c5c9c331914b'])
2022-08-24 22:10:29,952 __main__ INFO: 94:B9:7E:DA:7C:FE RSSI: -62, AdvertisementData(local_name='Long name works now', service_uuids=['4fafc201-1fb5-459e-8fcc-c5c9c331914b'])
2022-08-24 22:10:29,961 __main__ INFO: 94:B9:7E:DA:7C:FE RSSI: -60, AdvertisementData(local_name='Long name works now', service_uuids=['4fafc201-1fb5-459e-8fcc-c5c9c331914b'])
2022-08-24 22:10:30,171 __main__ INFO: 94:B9:7E:DA:7C:FE RSSI: -60, AdvertisementData(local_name='Long name works now', service_uuids=['4fafc201-1fb5
``` 

Everything seems to be working on my PC. However when I use the same `detection_callback.py` script including the service UUID  on my Mac, all I get is

```(re)starting scanner
(re)starting scanner
(re)starting scanner
```

Am I missing something obvious?

**Comment by dlech** [comment]
If you have a question, please start a discussion: https://github.com/hbldh/bleak/discussions

**Comment by damianjwilliams** [comment]
Oop, I accidentally posted the issue in the middle of writing it. I've updated it now.

**Comment by dlech** [comment]
> I know that when using MacOS 12.4, service UUIDs need to be provided to read advertising data (as discussed [extensively](https://github.com/hbldh/bleak/pull/692), but I am still struggling to get it to work.

Apple fixed the bug in 12.3, so it is no longer required.

> Am I missing something obvious?

Not that I can see. I've confirmed it is also not working on 12.5.1. I wonder if Apple introduced a new bug?

As a workaround, you can just leave out the service uuids.

**Comment by dlech** [comment]
After trying it a few more times, it is working again (I also started the Packet Logger app in the meantime). Not sure what could have been the difference from the times when I was able to reproduce the issue.

**Comment by damianjwilliams** [comment]
I just updated my MacOS from 12.4 to 12.5.1 and it seems to be working now! Thanks for your help.
