### ISSUE TITLE
Setting MTU during handshake

### ISSUE THREAD

**Issue by arasan90** [hbldh/bleak#97]
* bleak version: 0.4.3
* Python version: 3.7.4
* Operating System: Windows 10

I'd need to set a preferred MTU during the handshake with a device but I don't see this feature supported. Is it possible to add it?

**Comment by hbldh** [comment]
No, I am afraid not. The Windows UWP API for Bluetooth does not allow for user set MTU levels:
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d16679dc-48ed-4e29-83b1-cf281987f7dc/uwpblegattmtubluetooth-low-energy-ble-mtu-negotiations-issue?forum=wpdevelop

But as it says:
> Windows will always try to negotiate the maximum MTU size.  Effectively, this means that Windows will always request 525, then negotiate down to the maximum the device supports [...]
