### ISSUE TITLE
Timeout issue with Windows

### ISSUE THREAD

**Issue by Sebwap** [hbldh/bleak#98]
* bleak version: 0.5.0
* Python version: 3.7.3
* Operating System: Windows 10

### Description

I try to connect to a BLE device with a longer timeout than default (2s)
On windows 10, if I specify a longer timeout in connection string, like "async with BleakClient(address, loop=loop, timeout=5.0) as client:" in the sensor tag example, it doesn't work.

### What I Did

while using:
`async with BleakClient(address, loop=loop, timeout=5.0) as client:`
debug show:
poll 2000.000 ms took 2000.000 ms: timeout

```

**Comment by hbldh** [comment]
The `timeout` keyword only works on the `connect` method right now. Do
```
client = BleakClient(address, loop=loop)
client.connect(timeout=5.0)
# your code
client.disconnect()
```
instead of the `async with` context manager.

I had apparently missed the `with` usecase for the timeout parameter. I will remedy this in future release. Until then, try the code above.

**Comment by Sebwap** [comment]
Thanks for your answer.
It's working well now, even if I still have some "Device with address xx:xx:xx:xx:xx:xx was not found".
I suspect my device (Mi Flora) to be capricious, longer timeout doesn't change almost anything.
